version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - errname
    - errorlint
    - gocritic
    - gofumpt
    - govet
    - nilerr
    - prealloc
    - unconvert
    - unparam
    - unused
    - whitespace
formatters:
  enable:
    - gofumpt
