// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFieldUsage = `-- name: GetFieldUsage :many
SELECT tenant_id, field_path, period_start, read_count, last_read_by, last_read_at FROM usage_stats
WHERE tenant_id = $1
  AND field_path = $2
  AND ($3::TIMESTAMPTZ IS NULL OR period_start >= $3)
  AND ($4::TIMESTAMPTZ IS NULL OR period_start <= $4)
ORDER BY period_start DESC
`

type GetFieldUsageParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	FieldPath string             `json:"field_path"`
	Column3   pgtype.Timestamptz `json:"column_3"`
	Column4   pgtype.Timestamptz `json:"column_4"`
}

func (q *Queries) GetFieldUsage(ctx context.Context, arg GetFieldUsageParams) ([]UsageStat, error) {
	rows, err := q.db.Query(ctx, getFieldUsage,
		arg.TenantID,
		arg.FieldPath,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageStat{}
	for rows.Next() {
		var i UsageStat
		if err := rows.Scan(
			&i.TenantID,
			&i.FieldPath,
			&i.PeriodStart,
			&i.ReadCount,
			&i.LastReadBy,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantUsage = `-- name: GetTenantUsage :many
SELECT field_path, SUM(read_count) AS read_count,
       MAX(last_read_at) AS last_read_at
FROM usage_stats
WHERE tenant_id = $1
  AND ($2::TIMESTAMPTZ IS NULL OR period_start >= $2)
  AND ($3::TIMESTAMPTZ IS NULL OR period_start <= $3)
GROUP BY field_path
ORDER BY field_path
`

type GetTenantUsageParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	Column2  pgtype.Timestamptz `json:"column_2"`
	Column3  pgtype.Timestamptz `json:"column_3"`
}

type GetTenantUsageRow struct {
	FieldPath  string      `json:"field_path"`
	ReadCount  int64       `json:"read_count"`
	LastReadAt interface{} `json:"last_read_at"`
}

func (q *Queries) GetTenantUsage(ctx context.Context, arg GetTenantUsageParams) ([]GetTenantUsageRow, error) {
	rows, err := q.db.Query(ctx, getTenantUsage, arg.TenantID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTenantUsageRow{}
	for rows.Next() {
		var i GetTenantUsageRow
		if err := rows.Scan(&i.FieldPath, &i.ReadCount, &i.LastReadAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnusedFields = `-- name: GetUnusedFields :many
SELECT sf.path
FROM schema_fields sf
JOIN schema_versions sv ON sv.id = sf.schema_version_id
JOIN tenants t ON t.schema_id = sv.schema_id AND t.schema_version = sv.version
WHERE t.id = $1
  AND sf.path NOT IN (
      SELECT us.field_path FROM usage_stats us
      WHERE us.tenant_id = $1 AND us.last_read_at >= $2
  )
ORDER BY sf.path
`

type GetUnusedFieldsParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastReadAt pgtype.Timestamptz `json:"last_read_at"`
}

func (q *Queries) GetUnusedFields(ctx context.Context, arg GetUnusedFieldsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUnusedFields, arg.ID, arg.LastReadAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditWriteLog = `-- name: InsertAuditWriteLog :exec
INSERT INTO audit_write_log (tenant_id, actor, action, field_path, old_value, new_value, config_version, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditWriteLogParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Actor         string      `json:"actor"`
	Action        string      `json:"action"`
	FieldPath     *string     `json:"field_path"`
	OldValue      *string     `json:"old_value"`
	NewValue      *string     `json:"new_value"`
	ConfigVersion *int32      `json:"config_version"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditWriteLog(ctx context.Context, arg InsertAuditWriteLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditWriteLog,
		arg.TenantID,
		arg.Actor,
		arg.Action,
		arg.FieldPath,
		arg.OldValue,
		arg.NewValue,
		arg.ConfigVersion,
		arg.Metadata,
	)
	return err
}

const queryAuditWriteLog = `-- name: QueryAuditWriteLog :many
SELECT id, tenant_id, actor, action, field_path, old_value, new_value, config_version, metadata, created_at FROM audit_write_log
WHERE ($1::UUID IS NULL OR tenant_id = $1)
  AND (NULLIF($2::TEXT, '') IS NULL OR actor = $2)
  AND (NULLIF($3::TEXT, '') IS NULL OR field_path = $3)
  AND ($4::TIMESTAMPTZ IS NULL OR created_at >= $4)
  AND ($5::TIMESTAMPTZ IS NULL OR created_at <= $5)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type QueryAuditWriteLogParams struct {
	Column1 pgtype.UUID        `json:"column_1"`
	Column2 string             `json:"column_2"`
	Column3 string             `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Column5 pgtype.Timestamptz `json:"column_5"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) QueryAuditWriteLog(ctx context.Context, arg QueryAuditWriteLogParams) ([]AuditWriteLog, error) {
	rows, err := q.db.Query(ctx, queryAuditWriteLog,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditWriteLog{}
	for rows.Next() {
		var i AuditWriteLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Actor,
			&i.Action,
			&i.FieldPath,
			&i.OldValue,
			&i.NewValue,
			&i.ConfigVersion,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUsageStats = `-- name: UpsertUsageStats :exec
INSERT INTO usage_stats (tenant_id, field_path, period_start, read_count, last_read_by, last_read_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, field_path, period_start)
DO UPDATE SET
    read_count = usage_stats.read_count + EXCLUDED.read_count,
    last_read_by = EXCLUDED.last_read_by,
    last_read_at = EXCLUDED.last_read_at
`

type UpsertUsageStatsParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	FieldPath   string             `json:"field_path"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	ReadCount   int64              `json:"read_count"`
	LastReadBy  *string            `json:"last_read_by"`
	LastReadAt  pgtype.Timestamptz `json:"last_read_at"`
}

func (q *Queries) UpsertUsageStats(ctx context.Context, arg UpsertUsageStatsParams) error {
	_, err := q.db.Exec(ctx, upsertUsageStats,
		arg.TenantID,
		arg.FieldPath,
		arg.PeriodStart,
		arg.ReadCount,
		arg.LastReadBy,
		arg.LastReadAt,
	)
	return err
}
