// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package dbstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConfigVersion = `-- name: CreateConfigVersion :one
INSERT INTO config_versions (tenant_id, version, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, version, description, created_by, created_at
`

type CreateConfigVersionParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Version     int32       `json:"version"`
	Description *string     `json:"description"`
	CreatedBy   string      `json:"created_by"`
}

func (q *Queries) CreateConfigVersion(ctx context.Context, arg CreateConfigVersionParams) (ConfigVersion, error) {
	row := q.db.QueryRow(ctx, createConfigVersion,
		arg.TenantID,
		arg.Version,
		arg.Description,
		arg.CreatedBy,
	)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getConfigValueAtVersion = `-- name: GetConfigValueAtVersion :one
SELECT cv.field_path, cv.value, cv.description
FROM config_values cv
JOIN config_versions ver ON ver.id = cv.config_version_id
WHERE ver.tenant_id = $1
  AND cv.field_path = $2
  AND ver.version <= $3
ORDER BY ver.version DESC
LIMIT 1
`

type GetConfigValueAtVersionParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	FieldPath string      `json:"field_path"`
	Version   int32       `json:"version"`
}

type GetConfigValueAtVersionRow struct {
	FieldPath   string  `json:"field_path"`
	Value       string  `json:"value"`
	Description *string `json:"description"`
}

func (q *Queries) GetConfigValueAtVersion(ctx context.Context, arg GetConfigValueAtVersionParams) (GetConfigValueAtVersionRow, error) {
	row := q.db.QueryRow(ctx, getConfigValueAtVersion, arg.TenantID, arg.FieldPath, arg.Version)
	var i GetConfigValueAtVersionRow
	err := row.Scan(&i.FieldPath, &i.Value, &i.Description)
	return i, err
}

const getConfigValues = `-- name: GetConfigValues :many
SELECT config_version_id, field_path, value, description FROM config_values
WHERE config_version_id = $1
ORDER BY field_path
`

func (q *Queries) GetConfigValues(ctx context.Context, configVersionID pgtype.UUID) ([]ConfigValue, error) {
	rows, err := q.db.Query(ctx, getConfigValues, configVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigValue{}
	for rows.Next() {
		var i ConfigValue
		if err := rows.Scan(
			&i.ConfigVersionID,
			&i.FieldPath,
			&i.Value,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigVersion = `-- name: GetConfigVersion :one
SELECT id, tenant_id, version, description, created_by, created_at FROM config_versions
WHERE tenant_id = $1 AND version = $2
`

type GetConfigVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Version  int32       `json:"version"`
}

func (q *Queries) GetConfigVersion(ctx context.Context, arg GetConfigVersionParams) (ConfigVersion, error) {
	row := q.db.QueryRow(ctx, getConfigVersion, arg.TenantID, arg.Version)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getFullConfigAtVersion = `-- name: GetFullConfigAtVersion :many
SELECT DISTINCT ON (cv.field_path) cv.field_path, cv.value, cv.description
FROM config_values cv
JOIN config_versions ver ON ver.id = cv.config_version_id
WHERE ver.tenant_id = $1
  AND ver.version <= $2
ORDER BY cv.field_path, ver.version DESC
`

type GetFullConfigAtVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Version  int32       `json:"version"`
}

type GetFullConfigAtVersionRow struct {
	FieldPath   string  `json:"field_path"`
	Value       string  `json:"value"`
	Description *string `json:"description"`
}

func (q *Queries) GetFullConfigAtVersion(ctx context.Context, arg GetFullConfigAtVersionParams) ([]GetFullConfigAtVersionRow, error) {
	rows, err := q.db.Query(ctx, getFullConfigAtVersion, arg.TenantID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFullConfigAtVersionRow{}
	for rows.Next() {
		var i GetFullConfigAtVersionRow
		if err := rows.Scan(&i.FieldPath, &i.Value, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestConfigVersion = `-- name: GetLatestConfigVersion :one
SELECT id, tenant_id, version, description, created_by, created_at FROM config_versions
WHERE tenant_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestConfigVersion(ctx context.Context, tenantID pgtype.UUID) (ConfigVersion, error) {
	row := q.db.QueryRow(ctx, getLatestConfigVersion, tenantID)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listConfigVersions = `-- name: ListConfigVersions :many
SELECT id, tenant_id, version, description, created_by, created_at FROM config_versions
WHERE tenant_id = $1
ORDER BY version DESC
LIMIT $2 OFFSET $3
`

type ListConfigVersionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListConfigVersions(ctx context.Context, arg ListConfigVersionsParams) ([]ConfigVersion, error) {
	rows, err := q.db.Query(ctx, listConfigVersions, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigVersion{}
	for rows.Next() {
		var i ConfigVersion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Version,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConfigValue = `-- name: SetConfigValue :exec
INSERT INTO config_values (config_version_id, field_path, value, description)
VALUES ($1, $2, $3, $4)
`

type SetConfigValueParams struct {
	ConfigVersionID pgtype.UUID `json:"config_version_id"`
	FieldPath       string      `json:"field_path"`
	Value           string      `json:"value"`
	Description     *string     `json:"description"`
}

func (q *Queries) SetConfigValue(ctx context.Context, arg SetConfigValueParams) error {
	_, err := q.db.Exec(ctx, setConfigValue,
		arg.ConfigVersionID,
		arg.FieldPath,
		arg.Value,
		arg.Description,
	)
	return err
}
