// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbstore

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FieldType string

const (
	FieldTypeInteger  FieldType = "integer"
	FieldTypeNumber   FieldType = "number"
	FieldTypeString   FieldType = "string"
	FieldTypeBool     FieldType = "bool"
	FieldTypeTime     FieldType = "time"
	FieldTypeDuration FieldType = "duration"
	FieldTypeUrl      FieldType = "url"
	FieldTypeJson     FieldType = "json"
)

func (e *FieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FieldType(s)
	case string:
		*e = FieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for FieldType: %T", src)
	}
	return nil
}

type NullFieldType struct {
	FieldType FieldType `json:"field_type"`
	Valid     bool      `json:"valid"` // Valid is true if FieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.FieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FieldType), nil
}

type AuditWriteLog struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Actor         string             `json:"actor"`
	Action        string             `json:"action"`
	FieldPath     *string            `json:"field_path"`
	OldValue      *string            `json:"old_value"`
	NewValue      *string            `json:"new_value"`
	ConfigVersion *int32             `json:"config_version"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ConfigValue struct {
	ConfigVersionID pgtype.UUID `json:"config_version_id"`
	FieldPath       string      `json:"field_path"`
	Value           *string     `json:"value"`
	Checksum        *string     `json:"checksum"`
	Description     *string     `json:"description"`
}

type ConfigVersion struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Version     int32              `json:"version"`
	Description *string            `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Schema struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SchemaField struct {
	ID              pgtype.UUID `json:"id"`
	SchemaVersionID pgtype.UUID `json:"schema_version_id"`
	Path            string      `json:"path"`
	FieldType       FieldType   `json:"field_type"`
	Constraints     []byte      `json:"constraints"`
	Nullable        bool        `json:"nullable"`
	Deprecated      bool        `json:"deprecated"`
	RedirectTo      *string     `json:"redirect_to"`
	DefaultValue    *string     `json:"default_value"`
	Description     *string     `json:"description"`
	Title           *string     `json:"title"`
	Example         *string     `json:"example"`
	Examples        []byte      `json:"examples"`
	ExternalDocs    []byte      `json:"external_docs"`
	Tags            []string    `json:"tags"`
	Format          *string     `json:"format"`
	ReadOnly        bool        `json:"read_only"`
	WriteOnce       bool        `json:"write_once"`
	Sensitive       bool        `json:"sensitive"`
}

type SchemaVersion struct {
	ID            pgtype.UUID        `json:"id"`
	SchemaID      pgtype.UUID        `json:"schema_id"`
	Version       int32              `json:"version"`
	ParentVersion *int32             `json:"parent_version"`
	Description   *string            `json:"description"`
	Checksum      string             `json:"checksum"`
	Published     bool               `json:"published"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	SchemaID      pgtype.UUID        `json:"schema_id"`
	SchemaVersion int32              `json:"schema_version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TenantFieldLock struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	FieldPath    string      `json:"field_path"`
	LockedValues []byte      `json:"locked_values"`
}

type UsageStat struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	FieldPath   string             `json:"field_path"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	ReadCount   int64              `json:"read_count"`
	LastReadBy  *string            `json:"last_read_by"`
	LastReadAt  pgtype.Timestamptz `json:"last_read_at"`
}
