// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schemas.sql

package dbstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchema = `-- name: CreateSchema :one
INSERT INTO schemas (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateSchemaParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateSchema(ctx context.Context, arg CreateSchemaParams) (Schema, error) {
	row := q.db.QueryRow(ctx, createSchema, arg.Name, arg.Description)
	var i Schema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSchemaField = `-- name: CreateSchemaField :one
INSERT INTO schema_fields (schema_version_id, path, field_type, constraints, nullable, deprecated, redirect_to, default_value, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, schema_version_id, path, field_type, constraints, nullable, deprecated, redirect_to, default_value, description
`

type CreateSchemaFieldParams struct {
	SchemaVersionID pgtype.UUID `json:"schema_version_id"`
	Path            string      `json:"path"`
	FieldType       string      `json:"field_type"`
	Constraints     []byte      `json:"constraints"`
	Nullable        bool        `json:"nullable"`
	Deprecated      bool        `json:"deprecated"`
	RedirectTo      *string     `json:"redirect_to"`
	DefaultValue    *string     `json:"default_value"`
	Description     *string     `json:"description"`
}

func (q *Queries) CreateSchemaField(ctx context.Context, arg CreateSchemaFieldParams) (SchemaField, error) {
	row := q.db.QueryRow(ctx, createSchemaField,
		arg.SchemaVersionID,
		arg.Path,
		arg.FieldType,
		arg.Constraints,
		arg.Nullable,
		arg.Deprecated,
		arg.RedirectTo,
		arg.DefaultValue,
		arg.Description,
	)
	var i SchemaField
	err := row.Scan(
		&i.ID,
		&i.SchemaVersionID,
		&i.Path,
		&i.FieldType,
		&i.Constraints,
		&i.Nullable,
		&i.Deprecated,
		&i.RedirectTo,
		&i.DefaultValue,
		&i.Description,
	)
	return i, err
}

const createSchemaVersion = `-- name: CreateSchemaVersion :one
INSERT INTO schema_versions (schema_id, version, parent_version, description, checksum)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, schema_id, version, parent_version, description, checksum, published, created_at
`

type CreateSchemaVersionParams struct {
	SchemaID      pgtype.UUID `json:"schema_id"`
	Version       int32       `json:"version"`
	ParentVersion *int32      `json:"parent_version"`
	Description   *string     `json:"description"`
	Checksum      string      `json:"checksum"`
}

func (q *Queries) CreateSchemaVersion(ctx context.Context, arg CreateSchemaVersionParams) (SchemaVersion, error) {
	row := q.db.QueryRow(ctx, createSchemaVersion,
		arg.SchemaID,
		arg.Version,
		arg.ParentVersion,
		arg.Description,
		arg.Checksum,
	)
	var i SchemaVersion
	err := row.Scan(
		&i.ID,
		&i.SchemaID,
		&i.Version,
		&i.ParentVersion,
		&i.Description,
		&i.Checksum,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSchema = `-- name: DeleteSchema :exec
DELETE FROM schemas WHERE id = $1
`

func (q *Queries) DeleteSchema(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchema, id)
	return err
}

const deleteSchemaField = `-- name: DeleteSchemaField :exec
DELETE FROM schema_fields
WHERE schema_version_id = $1 AND path = $2
`

type DeleteSchemaFieldParams struct {
	SchemaVersionID pgtype.UUID `json:"schema_version_id"`
	Path            string      `json:"path"`
}

func (q *Queries) DeleteSchemaField(ctx context.Context, arg DeleteSchemaFieldParams) error {
	_, err := q.db.Exec(ctx, deleteSchemaField, arg.SchemaVersionID, arg.Path)
	return err
}

const getLatestSchemaVersion = `-- name: GetLatestSchemaVersion :one
SELECT id, schema_id, version, parent_version, description, checksum, published, created_at FROM schema_versions
WHERE schema_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestSchemaVersion(ctx context.Context, schemaID pgtype.UUID) (SchemaVersion, error) {
	row := q.db.QueryRow(ctx, getLatestSchemaVersion, schemaID)
	var i SchemaVersion
	err := row.Scan(
		&i.ID,
		&i.SchemaID,
		&i.Version,
		&i.ParentVersion,
		&i.Description,
		&i.Checksum,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getSchemaByID = `-- name: GetSchemaByID :one
SELECT id, name, description, created_at, updated_at FROM schemas WHERE id = $1
`

func (q *Queries) GetSchemaByID(ctx context.Context, id pgtype.UUID) (Schema, error) {
	row := q.db.QueryRow(ctx, getSchemaByID, id)
	var i Schema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchemaByName = `-- name: GetSchemaByName :one
SELECT id, name, description, created_at, updated_at FROM schemas WHERE name = $1
`

func (q *Queries) GetSchemaByName(ctx context.Context, name string) (Schema, error) {
	row := q.db.QueryRow(ctx, getSchemaByName, name)
	var i Schema
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchemaFields = `-- name: GetSchemaFields :many
SELECT id, schema_version_id, path, field_type, constraints, nullable, deprecated, redirect_to, default_value, description FROM schema_fields
WHERE schema_version_id = $1
ORDER BY path
`

func (q *Queries) GetSchemaFields(ctx context.Context, schemaVersionID pgtype.UUID) ([]SchemaField, error) {
	rows, err := q.db.Query(ctx, getSchemaFields, schemaVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemaField{}
	for rows.Next() {
		var i SchemaField
		if err := rows.Scan(
			&i.ID,
			&i.SchemaVersionID,
			&i.Path,
			&i.FieldType,
			&i.Constraints,
			&i.Nullable,
			&i.Deprecated,
			&i.RedirectTo,
			&i.DefaultValue,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT id, schema_id, version, parent_version, description, checksum, published, created_at FROM schema_versions
WHERE schema_id = $1 AND version = $2
`

type GetSchemaVersionParams struct {
	SchemaID pgtype.UUID `json:"schema_id"`
	Version  int32       `json:"version"`
}

func (q *Queries) GetSchemaVersion(ctx context.Context, arg GetSchemaVersionParams) (SchemaVersion, error) {
	row := q.db.QueryRow(ctx, getSchemaVersion, arg.SchemaID, arg.Version)
	var i SchemaVersion
	err := row.Scan(
		&i.ID,
		&i.SchemaID,
		&i.Version,
		&i.ParentVersion,
		&i.Description,
		&i.Checksum,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const listSchemas = `-- name: ListSchemas :many
SELECT id, name, description, created_at, updated_at FROM schemas
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSchemasParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSchemas(ctx context.Context, arg ListSchemasParams) ([]Schema, error) {
	rows, err := q.db.Query(ctx, listSchemas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schema{}
	for rows.Next() {
		var i Schema
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishSchemaVersion = `-- name: PublishSchemaVersion :one
UPDATE schema_versions SET published = true
WHERE schema_id = $1 AND version = $2
RETURNING id, schema_id, version, parent_version, description, checksum, published, created_at
`

type PublishSchemaVersionParams struct {
	SchemaID pgtype.UUID `json:"schema_id"`
	Version  int32       `json:"version"`
}

func (q *Queries) PublishSchemaVersion(ctx context.Context, arg PublishSchemaVersionParams) (SchemaVersion, error) {
	row := q.db.QueryRow(ctx, publishSchemaVersion, arg.SchemaID, arg.Version)
	var i SchemaVersion
	err := row.Scan(
		&i.ID,
		&i.SchemaID,
		&i.Version,
		&i.ParentVersion,
		&i.Description,
		&i.Checksum,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}
