// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package dbstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFieldLock = `-- name: CreateFieldLock :exec
INSERT INTO tenant_field_locks (tenant_id, field_path, locked_values)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, field_path) DO UPDATE SET locked_values = $3
`

type CreateFieldLockParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	FieldPath    string      `json:"field_path"`
	LockedValues []byte      `json:"locked_values"`
}

func (q *Queries) CreateFieldLock(ctx context.Context, arg CreateFieldLockParams) error {
	_, err := q.db.Exec(ctx, createFieldLock, arg.TenantID, arg.FieldPath, arg.LockedValues)
	return err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, schema_id, schema_version)
VALUES ($1, $2, $3)
RETURNING id, name, schema_id, schema_version, created_at, updated_at
`

type CreateTenantParams struct {
	Name          string      `json:"name"`
	SchemaID      pgtype.UUID `json:"schema_id"`
	SchemaVersion int32       `json:"schema_version"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.SchemaID, arg.SchemaVersion)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaID,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFieldLock = `-- name: DeleteFieldLock :exec
DELETE FROM tenant_field_locks
WHERE tenant_id = $1 AND field_path = $2
`

type DeleteFieldLockParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	FieldPath string      `json:"field_path"`
}

func (q *Queries) DeleteFieldLock(ctx context.Context, arg DeleteFieldLockParams) error {
	_, err := q.db.Exec(ctx, deleteFieldLock, arg.TenantID, arg.FieldPath)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getFieldLock = `-- name: GetFieldLock :one
SELECT tenant_id, field_path, locked_values FROM tenant_field_locks
WHERE tenant_id = $1 AND field_path = $2
`

type GetFieldLockParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	FieldPath string      `json:"field_path"`
}

func (q *Queries) GetFieldLock(ctx context.Context, arg GetFieldLockParams) (TenantFieldLock, error) {
	row := q.db.QueryRow(ctx, getFieldLock, arg.TenantID, arg.FieldPath)
	var i TenantFieldLock
	err := row.Scan(&i.TenantID, &i.FieldPath, &i.LockedValues)
	return i, err
}

const getFieldLocks = `-- name: GetFieldLocks :many
SELECT tenant_id, field_path, locked_values FROM tenant_field_locks
WHERE tenant_id = $1
ORDER BY field_path
`

func (q *Queries) GetFieldLocks(ctx context.Context, tenantID pgtype.UUID) ([]TenantFieldLock, error) {
	rows, err := q.db.Query(ctx, getFieldLocks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantFieldLock{}
	for rows.Next() {
		var i TenantFieldLock
		if err := rows.Scan(&i.TenantID, &i.FieldPath, &i.LockedValues); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, schema_id, schema_version, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaID,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, schema_id, schema_version, created_at, updated_at FROM tenants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SchemaID,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsBySchema = `-- name: ListTenantsBySchema :many
SELECT id, name, schema_id, schema_version, created_at, updated_at FROM tenants
WHERE schema_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTenantsBySchemaParams struct {
	SchemaID pgtype.UUID `json:"schema_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListTenantsBySchema(ctx context.Context, arg ListTenantsBySchemaParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsBySchema, arg.SchemaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SchemaID,
			&i.SchemaVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantName = `-- name: UpdateTenantName :one
UPDATE tenants SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, schema_id, schema_version, created_at, updated_at
`

type UpdateTenantNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateTenantName(ctx context.Context, arg UpdateTenantNameParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantName, arg.ID, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaID,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantSchemaVersion = `-- name: UpdateTenantSchemaVersion :one
UPDATE tenants SET schema_version = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, schema_id, schema_version, created_at, updated_at
`

type UpdateTenantSchemaVersionParams struct {
	ID            pgtype.UUID `json:"id"`
	SchemaVersion int32       `json:"schema_version"`
}

func (q *Queries) UpdateTenantSchemaVersion(ctx context.Context, arg UpdateTenantSchemaVersionParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantSchemaVersion, arg.ID, arg.SchemaVersion)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaID,
		&i.SchemaVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
