.nh
.TH "DECREE" "1" "Apr 2026" "OpenDecree" "OpenDecree CLI"

.SH NAME
decree-lock-remove - Unlock a field


.SH SYNOPSIS
\fBdecree lock remove   [flags]\fP


.SH DESCRIPTION
Unlock a field


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for remove


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--insecure\fP[=true]
	skip TLS verification

.PP
\fB-o\fP, \fB--output\fP="table"
	output format: table, json, yaml

.PP
\fB--role\fP="superadmin"
	actor role (x-role header)

.PP
\fB--server\fP="localhost:9090"
	gRPC server address

.PP
\fB--subject\fP=""
	actor identity (x-subject header)

.PP
\fB--tenant-id\fP=""
	auth tenant ID (x-tenant-id header)

.PP
\fB--token\fP=""
	JWT bearer token


.SH SEE ALSO
\fBdecree-lock(1)\fP
