.nh
.TH "DECREE" "1" "Apr 2026" "OpenDecree" "OpenDecree CLI"

.SH NAME
decree-dump - Export a full tenant backup (schema + config + locks)


.SH SYNOPSIS
\fBdecree dump  [flags]\fP


.SH DESCRIPTION
Dump exports a tenant's schema, configuration, and field locks as a single YAML file. The output is seed-compatible and can be used to recreate the tenant elsewhere.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for dump

.PP
\fB--no-locks\fP[=false]
	exclude field locks

.PP
\fB--output-file\fP=""
	write to file instead of stdout

.PP
\fB--version\fP=0
	config version (default: latest)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--insecure\fP[=true]
	skip TLS verification

.PP
\fB-o\fP, \fB--output\fP="table"
	output format: table, json, yaml

.PP
\fB--role\fP="superadmin"
	actor role (x-role header)

.PP
\fB--server\fP="localhost:9090"
	gRPC server address

.PP
\fB--subject\fP=""
	actor identity (x-subject header)

.PP
\fB--tenant-id\fP=""
	auth tenant ID (x-tenant-id header)

.PP
\fB--token\fP=""
	JWT bearer token


.SH SEE ALSO
\fBdecree(1)\fP
