// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: centralconfig/v1/audit_service.proto

package centralconfigv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_QueryWriteLog_FullMethodName   = "/centralconfig.v1.AuditService/QueryWriteLog"
	AuditService_GetFieldUsage_FullMethodName   = "/centralconfig.v1.AuditService/GetFieldUsage"
	AuditService_GetTenantUsage_FullMethodName  = "/centralconfig.v1.AuditService/GetTenantUsage"
	AuditService_GetUnusedFields_FullMethodName = "/centralconfig.v1.AuditService/GetUnusedFields"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuditService provides access to change history and usage statistics.
type AuditServiceClient interface {
	// Query write events (config changes).
	QueryWriteLog(ctx context.Context, in *QueryWriteLogRequest, opts ...grpc.CallOption) (*QueryWriteLogResponse, error)
	// Query read usage statistics.
	GetFieldUsage(ctx context.Context, in *GetFieldUsageRequest, opts ...grpc.CallOption) (*GetFieldUsageResponse, error)
	GetTenantUsage(ctx context.Context, in *GetTenantUsageRequest, opts ...grpc.CallOption) (*GetTenantUsageResponse, error)
	GetUnusedFields(ctx context.Context, in *GetUnusedFieldsRequest, opts ...grpc.CallOption) (*GetUnusedFieldsResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) QueryWriteLog(ctx context.Context, in *QueryWriteLogRequest, opts ...grpc.CallOption) (*QueryWriteLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryWriteLogResponse)
	err := c.cc.Invoke(ctx, AuditService_QueryWriteLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetFieldUsage(ctx context.Context, in *GetFieldUsageRequest, opts ...grpc.CallOption) (*GetFieldUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFieldUsageResponse)
	err := c.cc.Invoke(ctx, AuditService_GetFieldUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetTenantUsage(ctx context.Context, in *GetTenantUsageRequest, opts ...grpc.CallOption) (*GetTenantUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantUsageResponse)
	err := c.cc.Invoke(ctx, AuditService_GetTenantUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetUnusedFields(ctx context.Context, in *GetUnusedFieldsRequest, opts ...grpc.CallOption) (*GetUnusedFieldsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnusedFieldsResponse)
	err := c.cc.Invoke(ctx, AuditService_GetUnusedFields_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
//
// AuditService provides access to change history and usage statistics.
type AuditServiceServer interface {
	// Query write events (config changes).
	QueryWriteLog(context.Context, *QueryWriteLogRequest) (*QueryWriteLogResponse, error)
	// Query read usage statistics.
	GetFieldUsage(context.Context, *GetFieldUsageRequest) (*GetFieldUsageResponse, error)
	GetTenantUsage(context.Context, *GetTenantUsageRequest) (*GetTenantUsageResponse, error)
	GetUnusedFields(context.Context, *GetUnusedFieldsRequest) (*GetUnusedFieldsResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) QueryWriteLog(context.Context, *QueryWriteLogRequest) (*QueryWriteLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryWriteLog not implemented")
}
func (UnimplementedAuditServiceServer) GetFieldUsage(context.Context, *GetFieldUsageRequest) (*GetFieldUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFieldUsage not implemented")
}
func (UnimplementedAuditServiceServer) GetTenantUsage(context.Context, *GetTenantUsageRequest) (*GetTenantUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantUsage not implemented")
}
func (UnimplementedAuditServiceServer) GetUnusedFields(context.Context, *GetUnusedFieldsRequest) (*GetUnusedFieldsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnusedFields not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_QueryWriteLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWriteLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).QueryWriteLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_QueryWriteLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).QueryWriteLog(ctx, req.(*QueryWriteLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetFieldUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFieldUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetFieldUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetFieldUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetFieldUsage(ctx, req.(*GetFieldUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetTenantUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetTenantUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetTenantUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetTenantUsage(ctx, req.(*GetTenantUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetUnusedFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnusedFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetUnusedFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetUnusedFields_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetUnusedFields(ctx, req.(*GetUnusedFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "centralconfig.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryWriteLog",
			Handler:    _AuditService_QueryWriteLog_Handler,
		},
		{
			MethodName: "GetFieldUsage",
			Handler:    _AuditService_GetFieldUsage_Handler,
		},
		{
			MethodName: "GetTenantUsage",
			Handler:    _AuditService_GetTenantUsage_Handler,
		},
		{
			MethodName: "GetUnusedFields",
			Handler:    _AuditService_GetUnusedFields_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "centralconfig/v1/audit_service.proto",
}
