// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: centralconfig/v1/audit_service.proto

package centralconfigv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryWriteLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	Actor         *string                `protobuf:"bytes,2,opt,name=actor,proto3,oneof" json:"actor,omitempty"`
	FieldPath     *string                `protobuf:"bytes,3,opt,name=field_path,json=fieldPath,proto3,oneof" json:"field_path,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWriteLogRequest) Reset() {
	*x = QueryWriteLogRequest{}
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWriteLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWriteLogRequest) ProtoMessage() {}

func (x *QueryWriteLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWriteLogRequest.ProtoReflect.Descriptor instead.
func (*QueryWriteLogRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_audit_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryWriteLogRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *QueryWriteLogRequest) GetActor() string {
	if x != nil && x.Actor != nil {
		return *x.Actor
	}
	return ""
}

func (x *QueryWriteLogRequest) GetFieldPath() string {
	if x != nil && x.FieldPath != nil {
		return *x.FieldPath
	}
	return ""
}

func (x *QueryWriteLogRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryWriteLogRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryWriteLogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryWriteLogRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type QueryWriteLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWriteLogResponse) Reset() {
	*x = QueryWriteLogResponse{}
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWriteLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWriteLogResponse) ProtoMessage() {}

func (x *QueryWriteLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWriteLogResponse.ProtoReflect.Descriptor instead.
func (*QueryWriteLogResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_audit_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryWriteLogResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryWriteLogResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetFieldUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FieldPath     string                 `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldUsageRequest) Reset() {
	*x = GetFieldUsageRequest{}
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldUsageRequest) ProtoMessage() {}

func (x *GetFieldUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldUsageRequest.ProtoReflect.Descriptor instead.
func (*GetFieldUsageRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_audit_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetFieldUsageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetFieldUsageRequest) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *GetFieldUsageRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetFieldUsageRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetFieldUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *UsageStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldUsageResponse) Reset() {
	*x = GetFieldUsageResponse{}
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldUsageResponse) ProtoMessage() {}

func (x *GetFieldUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldUsageResponse.ProtoReflect.Descriptor instead.
func (*GetFieldUsageResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_audit_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetFieldUsageResponse) GetStats() *UsageStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetTenantUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantUsageRequest) Reset() {
	*x = GetTenantUsageRequest{}
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantUsageRequest) ProtoMessage() {}

func (x *GetTenantUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantUsageRequest.ProtoReflect.Descriptor instead.
func (*GetTenantUsageRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_audit_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantUsageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTenantUsageRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTenantUsageRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetTenantUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldStats    []*UsageStats          `protobuf:"bytes,1,rep,name=field_stats,json=fieldStats,proto3" json:"field_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantUsageResponse) Reset() {
	*x = GetTenantUsageResponse{}
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantUsageResponse) ProtoMessage() {}

func (x *GetTenantUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantUsageResponse.ProtoReflect.Descriptor instead.
func (*GetTenantUsageResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_audit_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantUsageResponse) GetFieldStats() []*UsageStats {
	if x != nil {
		return x.FieldStats
	}
	return nil
}

type GetUnusedFieldsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Fields not read since this time are considered unused.
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnusedFieldsRequest) Reset() {
	*x = GetUnusedFieldsRequest{}
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnusedFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnusedFieldsRequest) ProtoMessage() {}

func (x *GetUnusedFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnusedFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetUnusedFieldsRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_audit_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUnusedFieldsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetUnusedFieldsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type GetUnusedFieldsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPaths    []string               `protobuf:"bytes,1,rep,name=field_paths,json=fieldPaths,proto3" json:"field_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnusedFieldsResponse) Reset() {
	*x = GetUnusedFieldsResponse{}
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnusedFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnusedFieldsResponse) ProtoMessage() {}

func (x *GetUnusedFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_audit_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnusedFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetUnusedFieldsResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_audit_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUnusedFieldsResponse) GetFieldPaths() []string {
	if x != nil {
		return x.FieldPaths
	}
	return nil
}

var File_centralconfig_v1_audit_service_proto protoreflect.FileDescriptor

const file_centralconfig_v1_audit_service_proto_rawDesc = "" +
	"\n" +
	"$centralconfig/v1/audit_service.proto\x12\x10centralconfig.v1\x1a\x1ccentralconfig/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x02\n" +
	"\x14QueryWriteLogRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12\x19\n" +
	"\x05actor\x18\x02 \x01(\tH\x01R\x05actor\x88\x01\x01\x12\"\n" +
	"\n" +
	"field_path\x18\x03 \x01(\tH\x02R\tfieldPath\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\aendTime\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageTokenB\f\n" +
	"\n" +
	"_tenant_idB\b\n" +
	"\x06_actorB\r\n" +
	"\v_field_pathB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"w\n" +
	"\x15QueryWriteLogResponse\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.centralconfig.v1.AuditEntryR\aentries\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xea\x01\n" +
	"\x14GetFieldUsageRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\x12>\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01B\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"K\n" +
	"\x15GetFieldUsageResponse\x122\n" +
	"\x05stats\x18\x01 \x01(\v2\x1c.centralconfig.v1.UsageStatsR\x05stats\"\xcc\x01\n" +
	"\x15GetTenantUsageRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12>\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01B\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_time\"W\n" +
	"\x16GetTenantUsageResponse\x12=\n" +
	"\vfield_stats\x18\x01 \x03(\v2\x1c.centralconfig.v1.UsageStatsR\n" +
	"fieldStats\"g\n" +
	"\x16GetUnusedFieldsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\":\n" +
	"\x17GetUnusedFieldsResponse\x12\x1f\n" +
	"\vfield_paths\x18\x01 \x03(\tR\n" +
	"fieldPaths2\x9f\x03\n" +
	"\fAuditService\x12`\n" +
	"\rQueryWriteLog\x12&.centralconfig.v1.QueryWriteLogRequest\x1a'.centralconfig.v1.QueryWriteLogResponse\x12`\n" +
	"\rGetFieldUsage\x12&.centralconfig.v1.GetFieldUsageRequest\x1a'.centralconfig.v1.GetFieldUsageResponse\x12c\n" +
	"\x0eGetTenantUsage\x12'.centralconfig.v1.GetTenantUsageRequest\x1a(.centralconfig.v1.GetTenantUsageResponse\x12f\n" +
	"\x0fGetUnusedFields\x12(.centralconfig.v1.GetUnusedFieldsRequest\x1a).centralconfig.v1.GetUnusedFieldsResponseB\xd9\x01\n" +
	"\x14com.centralconfig.v1B\x11AuditServiceProtoP\x01ZMgithub.com/zeevdr/central-config-service/api/centralconfig/v1;centralconfigv1\xa2\x02\x03CXX\xaa\x02\x10Centralconfig.V1\xca\x02\x10Centralconfig\\V1\xe2\x02\x1cCentralconfig\\V1\\GPBMetadata\xea\x02\x11Centralconfig::V1b\x06proto3"

var (
	file_centralconfig_v1_audit_service_proto_rawDescOnce sync.Once
	file_centralconfig_v1_audit_service_proto_rawDescData []byte
)

func file_centralconfig_v1_audit_service_proto_rawDescGZIP() []byte {
	file_centralconfig_v1_audit_service_proto_rawDescOnce.Do(func() {
		file_centralconfig_v1_audit_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_centralconfig_v1_audit_service_proto_rawDesc), len(file_centralconfig_v1_audit_service_proto_rawDesc)))
	})
	return file_centralconfig_v1_audit_service_proto_rawDescData
}

var file_centralconfig_v1_audit_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_centralconfig_v1_audit_service_proto_goTypes = []any{
	(*QueryWriteLogRequest)(nil),    // 0: centralconfig.v1.QueryWriteLogRequest
	(*QueryWriteLogResponse)(nil),   // 1: centralconfig.v1.QueryWriteLogResponse
	(*GetFieldUsageRequest)(nil),    // 2: centralconfig.v1.GetFieldUsageRequest
	(*GetFieldUsageResponse)(nil),   // 3: centralconfig.v1.GetFieldUsageResponse
	(*GetTenantUsageRequest)(nil),   // 4: centralconfig.v1.GetTenantUsageRequest
	(*GetTenantUsageResponse)(nil),  // 5: centralconfig.v1.GetTenantUsageResponse
	(*GetUnusedFieldsRequest)(nil),  // 6: centralconfig.v1.GetUnusedFieldsRequest
	(*GetUnusedFieldsResponse)(nil), // 7: centralconfig.v1.GetUnusedFieldsResponse
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
	(*AuditEntry)(nil),              // 9: centralconfig.v1.AuditEntry
	(*UsageStats)(nil),              // 10: centralconfig.v1.UsageStats
}
var file_centralconfig_v1_audit_service_proto_depIdxs = []int32{
	8,  // 0: centralconfig.v1.QueryWriteLogRequest.start_time:type_name -> google.protobuf.Timestamp
	8,  // 1: centralconfig.v1.QueryWriteLogRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 2: centralconfig.v1.QueryWriteLogResponse.entries:type_name -> centralconfig.v1.AuditEntry
	8,  // 3: centralconfig.v1.GetFieldUsageRequest.start_time:type_name -> google.protobuf.Timestamp
	8,  // 4: centralconfig.v1.GetFieldUsageRequest.end_time:type_name -> google.protobuf.Timestamp
	10, // 5: centralconfig.v1.GetFieldUsageResponse.stats:type_name -> centralconfig.v1.UsageStats
	8,  // 6: centralconfig.v1.GetTenantUsageRequest.start_time:type_name -> google.protobuf.Timestamp
	8,  // 7: centralconfig.v1.GetTenantUsageRequest.end_time:type_name -> google.protobuf.Timestamp
	10, // 8: centralconfig.v1.GetTenantUsageResponse.field_stats:type_name -> centralconfig.v1.UsageStats
	8,  // 9: centralconfig.v1.GetUnusedFieldsRequest.since:type_name -> google.protobuf.Timestamp
	0,  // 10: centralconfig.v1.AuditService.QueryWriteLog:input_type -> centralconfig.v1.QueryWriteLogRequest
	2,  // 11: centralconfig.v1.AuditService.GetFieldUsage:input_type -> centralconfig.v1.GetFieldUsageRequest
	4,  // 12: centralconfig.v1.AuditService.GetTenantUsage:input_type -> centralconfig.v1.GetTenantUsageRequest
	6,  // 13: centralconfig.v1.AuditService.GetUnusedFields:input_type -> centralconfig.v1.GetUnusedFieldsRequest
	1,  // 14: centralconfig.v1.AuditService.QueryWriteLog:output_type -> centralconfig.v1.QueryWriteLogResponse
	3,  // 15: centralconfig.v1.AuditService.GetFieldUsage:output_type -> centralconfig.v1.GetFieldUsageResponse
	5,  // 16: centralconfig.v1.AuditService.GetTenantUsage:output_type -> centralconfig.v1.GetTenantUsageResponse
	7,  // 17: centralconfig.v1.AuditService.GetUnusedFields:output_type -> centralconfig.v1.GetUnusedFieldsResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_centralconfig_v1_audit_service_proto_init() }
func file_centralconfig_v1_audit_service_proto_init() {
	if File_centralconfig_v1_audit_service_proto != nil {
		return
	}
	file_centralconfig_v1_types_proto_init()
	file_centralconfig_v1_audit_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_centralconfig_v1_audit_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_centralconfig_v1_audit_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_centralconfig_v1_audit_service_proto_rawDesc), len(file_centralconfig_v1_audit_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_centralconfig_v1_audit_service_proto_goTypes,
		DependencyIndexes: file_centralconfig_v1_audit_service_proto_depIdxs,
		MessageInfos:      file_centralconfig_v1_audit_service_proto_msgTypes,
	}.Build()
	File_centralconfig_v1_audit_service_proto = out.File
	file_centralconfig_v1_audit_service_proto_goTypes = nil
	file_centralconfig_v1_audit_service_proto_depIdxs = nil
}
