// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: centralconfig/v1/config_service.proto

package centralconfigv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImportMode controls how imported values interact with existing config.
type ImportMode int32

const (
	// Unspecified defaults to merge behavior.
	ImportMode_IMPORT_MODE_UNSPECIFIED ImportMode = 0
	// Merge: update fields from YAML that differ, keep runtime overrides
	// for fields not in the YAML.
	ImportMode_IMPORT_MODE_MERGE ImportMode = 1
	// Replace: full replace — all fields from YAML are set, fields not in YAML
	// are not carried forward. Runtime overrides are wiped.
	ImportMode_IMPORT_MODE_REPLACE ImportMode = 2
	// Defaults: only set fields that have no value yet. Fields that already have
	// a value are skipped regardless of the YAML content.
	ImportMode_IMPORT_MODE_DEFAULTS ImportMode = 3
)

// Enum value maps for ImportMode.
var (
	ImportMode_name = map[int32]string{
		0: "IMPORT_MODE_UNSPECIFIED",
		1: "IMPORT_MODE_MERGE",
		2: "IMPORT_MODE_REPLACE",
		3: "IMPORT_MODE_DEFAULTS",
	}
	ImportMode_value = map[string]int32{
		"IMPORT_MODE_UNSPECIFIED": 0,
		"IMPORT_MODE_MERGE":       1,
		"IMPORT_MODE_REPLACE":     2,
		"IMPORT_MODE_DEFAULTS":    3,
	}
)

func (x ImportMode) Enum() *ImportMode {
	p := new(ImportMode)
	*p = x
	return p
}

func (x ImportMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportMode) Descriptor() protoreflect.EnumDescriptor {
	return file_centralconfig_v1_config_service_proto_enumTypes[0].Descriptor()
}

func (ImportMode) Type() protoreflect.EnumType {
	return &file_centralconfig_v1_config_service_proto_enumTypes[0]
}

func (x ImportMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportMode.Descriptor instead.
func (ImportMode) EnumDescriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{0}
}

type GetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Config version to retrieve. If omitted, returns the latest version.
	Version *int32 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// When true, includes value-level descriptions in the response.
	// This bypasses the Redis cache and reads directly from the database.
	IncludeDescriptions bool `protobuf:"varint,3,opt,name=include_descriptions,json=includeDescriptions,proto3" json:"include_descriptions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetConfigRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *GetConfigRequest) GetIncludeDescriptions() bool {
	if x != nil {
		return x.IncludeDescriptions
	}
	return false
}

type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full resolved configuration at the requested version.
	Config        *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetFieldRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Dot-separated field path (e.g. "payments.fee").
	FieldPath string `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// Config version to read from. If omitted, reads from the latest version.
	Version *int32 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// When true, includes the value-level description.
	// This bypasses the Redis cache and reads directly from the database.
	IncludeDescription bool `protobuf:"varint,4,opt,name=include_description,json=includeDescription,proto3" json:"include_description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetFieldRequest) Reset() {
	*x = GetFieldRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldRequest) ProtoMessage() {}

func (x *GetFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldRequest.ProtoReflect.Descriptor instead.
func (*GetFieldRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetFieldRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetFieldRequest) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *GetFieldRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *GetFieldRequest) GetIncludeDescription() bool {
	if x != nil {
		return x.IncludeDescription
	}
	return false
}

type GetFieldResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The configuration value. Returns NOT_FOUND if the field has no value set.
	Value         *ConfigValue `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldResponse) Reset() {
	*x = GetFieldResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldResponse) ProtoMessage() {}

func (x *GetFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldResponse.ProtoReflect.Descriptor instead.
func (*GetFieldResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetFieldResponse) GetValue() *ConfigValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Dot-separated field paths to retrieve.
	FieldPaths []string `protobuf:"bytes,2,rep,name=field_paths,json=fieldPaths,proto3" json:"field_paths,omitempty"`
	// Config version to read from. If omitted, reads from the latest version.
	Version *int32 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// When true, includes value-level descriptions.
	// This bypasses the Redis cache and reads directly from the database.
	IncludeDescriptions bool `protobuf:"varint,4,opt,name=include_descriptions,json=includeDescriptions,proto3" json:"include_descriptions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetFieldsRequest) Reset() {
	*x = GetFieldsRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsRequest) ProtoMessage() {}

func (x *GetFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetFieldsRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetFieldsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetFieldsRequest) GetFieldPaths() []string {
	if x != nil {
		return x.FieldPaths
	}
	return nil
}

func (x *GetFieldsRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *GetFieldsRequest) GetIncludeDescriptions() bool {
	if x != nil {
		return x.IncludeDescriptions
	}
	return false
}

type GetFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested values. Fields that don't exist are omitted (not an error).
	Values        []*ConfigValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFieldsResponse) Reset() {
	*x = GetFieldsResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFieldsResponse) ProtoMessage() {}

func (x *GetFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetFieldsResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetFieldsResponse) GetValues() []*ConfigValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type SetFieldRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Dot-separated field path (e.g. "payments.fee").
	FieldPath string `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// The typed value. Omit to set the field to null.
	Value *TypedValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Optimistic concurrency control: the checksum from a previous GetField/GetConfig
	// response. If provided and the field's current checksum doesn't match, the
	// request fails with ABORTED. This prevents lost updates when multiple actors
	// modify the same field concurrently.
	ExpectedChecksum *string `protobuf:"bytes,4,opt,name=expected_checksum,json=expectedChecksum,proto3,oneof" json:"expected_checksum,omitempty"`
	// Version-level description explaining why this change was made.
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Value-level description explaining what this specific value means.
	// Retrievable via include_description in read requests.
	ValueDescription *string `protobuf:"bytes,6,opt,name=value_description,json=valueDescription,proto3,oneof" json:"value_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetFieldRequest) Reset() {
	*x = SetFieldRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFieldRequest) ProtoMessage() {}

func (x *SetFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFieldRequest.ProtoReflect.Descriptor instead.
func (*SetFieldRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetFieldRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SetFieldRequest) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *SetFieldRequest) GetValue() *TypedValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetFieldRequest) GetExpectedChecksum() string {
	if x != nil && x.ExpectedChecksum != nil {
		return *x.ExpectedChecksum
	}
	return ""
}

func (x *SetFieldRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *SetFieldRequest) GetValueDescription() string {
	if x != nil && x.ValueDescription != nil {
		return *x.ValueDescription
	}
	return ""
}

type SetFieldResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created config version.
	ConfigVersion *ConfigVersion `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFieldResponse) Reset() {
	*x = SetFieldResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFieldResponse) ProtoMessage() {}

func (x *SetFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFieldResponse.ProtoReflect.Descriptor instead.
func (*SetFieldResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetFieldResponse) GetConfigVersion() *ConfigVersion {
	if x != nil {
		return x.ConfigVersion
	}
	return nil
}

type SetFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Field updates to apply. All updates are applied atomically in a single
	// config version. If any update fails validation (checksum, field lock),
	// no changes are committed.
	Updates []*FieldUpdate `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	// Version-level description explaining why these changes were made.
	Description   *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFieldsRequest) Reset() {
	*x = SetFieldsRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFieldsRequest) ProtoMessage() {}

func (x *SetFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFieldsRequest.ProtoReflect.Descriptor instead.
func (*SetFieldsRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{8}
}

func (x *SetFieldsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SetFieldsRequest) GetUpdates() []*FieldUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *SetFieldsRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type SetFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created config version.
	ConfigVersion *ConfigVersion `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFieldsResponse) Reset() {
	*x = SetFieldsResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFieldsResponse) ProtoMessage() {}

func (x *SetFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFieldsResponse.ProtoReflect.Descriptor instead.
func (*SetFieldsResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{9}
}

func (x *SetFieldsResponse) GetConfigVersion() *ConfigVersion {
	if x != nil {
		return x.ConfigVersion
	}
	return nil
}

// FieldUpdate represents a single field change within a SetFields batch.
type FieldUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dot-separated field path.
	FieldPath string `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// The typed value. Omit to set the field to null.
	Value *TypedValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Optimistic concurrency control checksum for this specific field.
	// See SetFieldRequest.expected_checksum for details.
	ExpectedChecksum *string `protobuf:"bytes,3,opt,name=expected_checksum,json=expectedChecksum,proto3,oneof" json:"expected_checksum,omitempty"`
	// Value-level description for this specific field.
	ValueDescription *string `protobuf:"bytes,4,opt,name=value_description,json=valueDescription,proto3,oneof" json:"value_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FieldUpdate) Reset() {
	*x = FieldUpdate{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldUpdate) ProtoMessage() {}

func (x *FieldUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldUpdate.ProtoReflect.Descriptor instead.
func (*FieldUpdate) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{10}
}

func (x *FieldUpdate) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *FieldUpdate) GetValue() *TypedValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FieldUpdate) GetExpectedChecksum() string {
	if x != nil && x.ExpectedChecksum != nil {
		return *x.ExpectedChecksum
	}
	return ""
}

func (x *FieldUpdate) GetValueDescription() string {
	if x != nil && x.ValueDescription != nil {
		return *x.ValueDescription
	}
	return ""
}

type ListVersionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Maximum number of results to return. Defaults to 50, max 100.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from a previous ListVersionsResponse.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListVersionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVersionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListVersionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config versions, ordered by version number descending (newest first).
	Versions []*ConfigVersion `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	// Token for the next page. Empty if no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListVersionsResponse) GetVersions() []*ConfigVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListVersionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The version number to retrieve.
	Version       int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetVersionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetVersionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion *ConfigVersion         `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetVersionResponse) GetConfigVersion() *ConfigVersion {
	if x != nil {
		return x.ConfigVersion
	}
	return nil
}

type RollbackToVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The target version to rollback to. The full config at this version
	// is copied into a new version (the current version number + 1).
	// The target version itself is not modified.
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Description for the new rollback version. Defaults to
	// "Rollback to version N" if omitted.
	Description   *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackToVersionRequest) Reset() {
	*x = RollbackToVersionRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackToVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackToVersionRequest) ProtoMessage() {}

func (x *RollbackToVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackToVersionRequest.ProtoReflect.Descriptor instead.
func (*RollbackToVersionRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{15}
}

func (x *RollbackToVersionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RollbackToVersionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RollbackToVersionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type RollbackToVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created config version containing the rolled-back values.
	ConfigVersion *ConfigVersion `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackToVersionResponse) Reset() {
	*x = RollbackToVersionResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackToVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackToVersionResponse) ProtoMessage() {}

func (x *RollbackToVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackToVersionResponse.ProtoReflect.Descriptor instead.
func (*RollbackToVersionResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{16}
}

func (x *RollbackToVersionResponse) GetConfigVersion() *ConfigVersion {
	if x != nil {
		return x.ConfigVersion
	}
	return nil
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID) to subscribe to.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Field paths to filter on. If empty, receives changes for all fields.
	// Changes to fields not in this list are silently dropped.
	FieldPaths    []string `protobuf:"bytes,2,rep,name=field_paths,json=fieldPaths,proto3" json:"field_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{17}
}

func (x *SubscribeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubscribeRequest) GetFieldPaths() []string {
	if x != nil {
		return x.FieldPaths
	}
	return nil
}

type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A configuration change event. Delivered via Redis Pub/Sub internally.
	Change        *ConfigChange `protobuf:"bytes,1,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{18}
}

func (x *SubscribeResponse) GetChange() *ConfigChange {
	if x != nil {
		return x.Change
	}
	return nil
}

type ExportConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Config version to export. If omitted, exports the latest version.
	Version       *int32 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportConfigRequest) Reset() {
	*x = ExportConfigRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportConfigRequest) ProtoMessage() {}

func (x *ExportConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportConfigRequest.ProtoReflect.Descriptor instead.
func (*ExportConfigRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{19}
}

func (x *ExportConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExportConfigRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type ExportConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// YAML-encoded configuration values.
	YamlContent   []byte `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportConfigResponse) Reset() {
	*x = ExportConfigResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportConfigResponse) ProtoMessage() {}

func (x *ExportConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportConfigResponse.ProtoReflect.Descriptor instead.
func (*ExportConfigResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{20}
}

func (x *ExportConfigResponse) GetYamlContent() []byte {
	if x != nil {
		return x.YamlContent
	}
	return nil
}

type ImportConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// YAML-encoded configuration values to import.
	YamlContent []byte `protobuf:"bytes,2,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	// Description for the new config version created by the import.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Import mode. Defaults to IMPORT_MODE_MERGE.
	Mode          ImportMode `protobuf:"varint,4,opt,name=mode,proto3,enum=centralconfig.v1.ImportMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportConfigRequest) Reset() {
	*x = ImportConfigRequest{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportConfigRequest) ProtoMessage() {}

func (x *ImportConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportConfigRequest.ProtoReflect.Descriptor instead.
func (*ImportConfigRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{21}
}

func (x *ImportConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ImportConfigRequest) GetYamlContent() []byte {
	if x != nil {
		return x.YamlContent
	}
	return nil
}

func (x *ImportConfigRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ImportConfigRequest) GetMode() ImportMode {
	if x != nil {
		return x.Mode
	}
	return ImportMode_IMPORT_MODE_UNSPECIFIED
}

type ImportConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The config version created by the import.
	ConfigVersion *ConfigVersion `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportConfigResponse) Reset() {
	*x = ImportConfigResponse{}
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportConfigResponse) ProtoMessage() {}

func (x *ImportConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_config_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportConfigResponse.ProtoReflect.Descriptor instead.
func (*ImportConfigResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_config_service_proto_rawDescGZIP(), []int{22}
}

func (x *ImportConfigResponse) GetConfigVersion() *ConfigVersion {
	if x != nil {
		return x.ConfigVersion
	}
	return nil
}

var File_centralconfig_v1_config_service_proto protoreflect.FileDescriptor

const file_centralconfig_v1_config_service_proto_rawDesc = "" +
	"\n" +
	"%centralconfig/v1/config_service.proto\x12\x10centralconfig.v1\x1a\x1ccentralconfig/v1/types.proto\"\x8d\x01\n" +
	"\x10GetConfigRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\x05H\x00R\aversion\x88\x01\x01\x121\n" +
	"\x14include_descriptions\x18\x03 \x01(\bR\x13includeDescriptionsB\n" +
	"\n" +
	"\b_version\"E\n" +
	"\x11GetConfigResponse\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.centralconfig.v1.ConfigR\x06config\"\xa9\x01\n" +
	"\x0fGetFieldRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x05H\x00R\aversion\x88\x01\x01\x12/\n" +
	"\x13include_description\x18\x04 \x01(\bR\x12includeDescriptionB\n" +
	"\n" +
	"\b_version\"G\n" +
	"\x10GetFieldResponse\x123\n" +
	"\x05value\x18\x01 \x01(\v2\x1d.centralconfig.v1.ConfigValueR\x05value\"\xae\x01\n" +
	"\x10GetFieldsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vfield_paths\x18\x02 \x03(\tR\n" +
	"fieldPaths\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x05H\x00R\aversion\x88\x01\x01\x121\n" +
	"\x14include_descriptions\x18\x04 \x01(\bR\x13includeDescriptionsB\n" +
	"\n" +
	"\b_version\"J\n" +
	"\x11GetFieldsResponse\x125\n" +
	"\x06values\x18\x01 \x03(\v2\x1d.centralconfig.v1.ConfigValueR\x06values\"\xc8\x02\n" +
	"\x0fSetFieldRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\x122\n" +
	"\x05value\x18\x03 \x01(\v2\x1c.centralconfig.v1.TypedValueR\x05value\x120\n" +
	"\x11expected_checksum\x18\x04 \x01(\tH\x00R\x10expectedChecksum\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x120\n" +
	"\x11value_description\x18\x06 \x01(\tH\x02R\x10valueDescription\x88\x01\x01B\x14\n" +
	"\x12_expected_checksumB\x0e\n" +
	"\f_descriptionB\x14\n" +
	"\x12_value_description\"Z\n" +
	"\x10SetFieldResponse\x12F\n" +
	"\x0econfig_version\x18\x01 \x01(\v2\x1f.centralconfig.v1.ConfigVersionR\rconfigVersion\"\x9f\x01\n" +
	"\x10SetFieldsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x127\n" +
	"\aupdates\x18\x02 \x03(\v2\x1d.centralconfig.v1.FieldUpdateR\aupdates\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"[\n" +
	"\x11SetFieldsResponse\x12F\n" +
	"\x0econfig_version\x18\x01 \x01(\v2\x1f.centralconfig.v1.ConfigVersionR\rconfigVersion\"\xf0\x01\n" +
	"\vFieldUpdate\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.centralconfig.v1.TypedValueR\x05value\x120\n" +
	"\x11expected_checksum\x18\x03 \x01(\tH\x00R\x10expectedChecksum\x88\x01\x01\x120\n" +
	"\x11value_description\x18\x04 \x01(\tH\x01R\x10valueDescription\x88\x01\x01B\x14\n" +
	"\x12_expected_checksumB\x14\n" +
	"\x12_value_description\"n\n" +
	"\x13ListVersionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"{\n" +
	"\x14ListVersionsResponse\x12;\n" +
	"\bversions\x18\x01 \x03(\v2\x1f.centralconfig.v1.ConfigVersionR\bversions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"J\n" +
	"\x11GetVersionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\\\n" +
	"\x12GetVersionResponse\x12F\n" +
	"\x0econfig_version\x18\x01 \x01(\v2\x1f.centralconfig.v1.ConfigVersionR\rconfigVersion\"\x88\x01\n" +
	"\x18RollbackToVersionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"c\n" +
	"\x19RollbackToVersionResponse\x12F\n" +
	"\x0econfig_version\x18\x01 \x01(\v2\x1f.centralconfig.v1.ConfigVersionR\rconfigVersion\"P\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vfield_paths\x18\x02 \x03(\tR\n" +
	"fieldPaths\"K\n" +
	"\x11SubscribeResponse\x126\n" +
	"\x06change\x18\x01 \x01(\v2\x1e.centralconfig.v1.ConfigChangeR\x06change\"]\n" +
	"\x13ExportConfigRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\x05H\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"9\n" +
	"\x14ExportConfigResponse\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\fR\vyamlContent\"\xbe\x01\n" +
	"\x13ImportConfigRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fyaml_content\x18\x02 \x01(\fR\vyamlContent\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x120\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1c.centralconfig.v1.ImportModeR\x04modeB\x0e\n" +
	"\f_description\"^\n" +
	"\x14ImportConfigResponse\x12F\n" +
	"\x0econfig_version\x18\x01 \x01(\v2\x1f.centralconfig.v1.ConfigVersionR\rconfigVersion*s\n" +
	"\n" +
	"ImportMode\x12\x1b\n" +
	"\x17IMPORT_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11IMPORT_MODE_MERGE\x10\x01\x12\x17\n" +
	"\x13IMPORT_MODE_REPLACE\x10\x02\x12\x18\n" +
	"\x14IMPORT_MODE_DEFAULTS\x10\x032\xf3\a\n" +
	"\rConfigService\x12T\n" +
	"\tGetConfig\x12\".centralconfig.v1.GetConfigRequest\x1a#.centralconfig.v1.GetConfigResponse\x12Q\n" +
	"\bGetField\x12!.centralconfig.v1.GetFieldRequest\x1a\".centralconfig.v1.GetFieldResponse\x12T\n" +
	"\tGetFields\x12\".centralconfig.v1.GetFieldsRequest\x1a#.centralconfig.v1.GetFieldsResponse\x12Q\n" +
	"\bSetField\x12!.centralconfig.v1.SetFieldRequest\x1a\".centralconfig.v1.SetFieldResponse\x12T\n" +
	"\tSetFields\x12\".centralconfig.v1.SetFieldsRequest\x1a#.centralconfig.v1.SetFieldsResponse\x12]\n" +
	"\fListVersions\x12%.centralconfig.v1.ListVersionsRequest\x1a&.centralconfig.v1.ListVersionsResponse\x12W\n" +
	"\n" +
	"GetVersion\x12#.centralconfig.v1.GetVersionRequest\x1a$.centralconfig.v1.GetVersionResponse\x12l\n" +
	"\x11RollbackToVersion\x12*.centralconfig.v1.RollbackToVersionRequest\x1a+.centralconfig.v1.RollbackToVersionResponse\x12V\n" +
	"\tSubscribe\x12\".centralconfig.v1.SubscribeRequest\x1a#.centralconfig.v1.SubscribeResponse0\x01\x12]\n" +
	"\fExportConfig\x12%.centralconfig.v1.ExportConfigRequest\x1a&.centralconfig.v1.ExportConfigResponse\x12]\n" +
	"\fImportConfig\x12%.centralconfig.v1.ImportConfigRequest\x1a&.centralconfig.v1.ImportConfigResponseB\xda\x01\n" +
	"\x14com.centralconfig.v1B\x12ConfigServiceProtoP\x01ZMgithub.com/zeevdr/central-config-service/api/centralconfig/v1;centralconfigv1\xa2\x02\x03CXX\xaa\x02\x10Centralconfig.V1\xca\x02\x10Centralconfig\\V1\xe2\x02\x1cCentralconfig\\V1\\GPBMetadata\xea\x02\x11Centralconfig::V1b\x06proto3"

var (
	file_centralconfig_v1_config_service_proto_rawDescOnce sync.Once
	file_centralconfig_v1_config_service_proto_rawDescData []byte
)

func file_centralconfig_v1_config_service_proto_rawDescGZIP() []byte {
	file_centralconfig_v1_config_service_proto_rawDescOnce.Do(func() {
		file_centralconfig_v1_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_centralconfig_v1_config_service_proto_rawDesc), len(file_centralconfig_v1_config_service_proto_rawDesc)))
	})
	return file_centralconfig_v1_config_service_proto_rawDescData
}

var file_centralconfig_v1_config_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_centralconfig_v1_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_centralconfig_v1_config_service_proto_goTypes = []any{
	(ImportMode)(0),                   // 0: centralconfig.v1.ImportMode
	(*GetConfigRequest)(nil),          // 1: centralconfig.v1.GetConfigRequest
	(*GetConfigResponse)(nil),         // 2: centralconfig.v1.GetConfigResponse
	(*GetFieldRequest)(nil),           // 3: centralconfig.v1.GetFieldRequest
	(*GetFieldResponse)(nil),          // 4: centralconfig.v1.GetFieldResponse
	(*GetFieldsRequest)(nil),          // 5: centralconfig.v1.GetFieldsRequest
	(*GetFieldsResponse)(nil),         // 6: centralconfig.v1.GetFieldsResponse
	(*SetFieldRequest)(nil),           // 7: centralconfig.v1.SetFieldRequest
	(*SetFieldResponse)(nil),          // 8: centralconfig.v1.SetFieldResponse
	(*SetFieldsRequest)(nil),          // 9: centralconfig.v1.SetFieldsRequest
	(*SetFieldsResponse)(nil),         // 10: centralconfig.v1.SetFieldsResponse
	(*FieldUpdate)(nil),               // 11: centralconfig.v1.FieldUpdate
	(*ListVersionsRequest)(nil),       // 12: centralconfig.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),      // 13: centralconfig.v1.ListVersionsResponse
	(*GetVersionRequest)(nil),         // 14: centralconfig.v1.GetVersionRequest
	(*GetVersionResponse)(nil),        // 15: centralconfig.v1.GetVersionResponse
	(*RollbackToVersionRequest)(nil),  // 16: centralconfig.v1.RollbackToVersionRequest
	(*RollbackToVersionResponse)(nil), // 17: centralconfig.v1.RollbackToVersionResponse
	(*SubscribeRequest)(nil),          // 18: centralconfig.v1.SubscribeRequest
	(*SubscribeResponse)(nil),         // 19: centralconfig.v1.SubscribeResponse
	(*ExportConfigRequest)(nil),       // 20: centralconfig.v1.ExportConfigRequest
	(*ExportConfigResponse)(nil),      // 21: centralconfig.v1.ExportConfigResponse
	(*ImportConfigRequest)(nil),       // 22: centralconfig.v1.ImportConfigRequest
	(*ImportConfigResponse)(nil),      // 23: centralconfig.v1.ImportConfigResponse
	(*Config)(nil),                    // 24: centralconfig.v1.Config
	(*ConfigValue)(nil),               // 25: centralconfig.v1.ConfigValue
	(*TypedValue)(nil),                // 26: centralconfig.v1.TypedValue
	(*ConfigVersion)(nil),             // 27: centralconfig.v1.ConfigVersion
	(*ConfigChange)(nil),              // 28: centralconfig.v1.ConfigChange
}
var file_centralconfig_v1_config_service_proto_depIdxs = []int32{
	24, // 0: centralconfig.v1.GetConfigResponse.config:type_name -> centralconfig.v1.Config
	25, // 1: centralconfig.v1.GetFieldResponse.value:type_name -> centralconfig.v1.ConfigValue
	25, // 2: centralconfig.v1.GetFieldsResponse.values:type_name -> centralconfig.v1.ConfigValue
	26, // 3: centralconfig.v1.SetFieldRequest.value:type_name -> centralconfig.v1.TypedValue
	27, // 4: centralconfig.v1.SetFieldResponse.config_version:type_name -> centralconfig.v1.ConfigVersion
	11, // 5: centralconfig.v1.SetFieldsRequest.updates:type_name -> centralconfig.v1.FieldUpdate
	27, // 6: centralconfig.v1.SetFieldsResponse.config_version:type_name -> centralconfig.v1.ConfigVersion
	26, // 7: centralconfig.v1.FieldUpdate.value:type_name -> centralconfig.v1.TypedValue
	27, // 8: centralconfig.v1.ListVersionsResponse.versions:type_name -> centralconfig.v1.ConfigVersion
	27, // 9: centralconfig.v1.GetVersionResponse.config_version:type_name -> centralconfig.v1.ConfigVersion
	27, // 10: centralconfig.v1.RollbackToVersionResponse.config_version:type_name -> centralconfig.v1.ConfigVersion
	28, // 11: centralconfig.v1.SubscribeResponse.change:type_name -> centralconfig.v1.ConfigChange
	0,  // 12: centralconfig.v1.ImportConfigRequest.mode:type_name -> centralconfig.v1.ImportMode
	27, // 13: centralconfig.v1.ImportConfigResponse.config_version:type_name -> centralconfig.v1.ConfigVersion
	1,  // 14: centralconfig.v1.ConfigService.GetConfig:input_type -> centralconfig.v1.GetConfigRequest
	3,  // 15: centralconfig.v1.ConfigService.GetField:input_type -> centralconfig.v1.GetFieldRequest
	5,  // 16: centralconfig.v1.ConfigService.GetFields:input_type -> centralconfig.v1.GetFieldsRequest
	7,  // 17: centralconfig.v1.ConfigService.SetField:input_type -> centralconfig.v1.SetFieldRequest
	9,  // 18: centralconfig.v1.ConfigService.SetFields:input_type -> centralconfig.v1.SetFieldsRequest
	12, // 19: centralconfig.v1.ConfigService.ListVersions:input_type -> centralconfig.v1.ListVersionsRequest
	14, // 20: centralconfig.v1.ConfigService.GetVersion:input_type -> centralconfig.v1.GetVersionRequest
	16, // 21: centralconfig.v1.ConfigService.RollbackToVersion:input_type -> centralconfig.v1.RollbackToVersionRequest
	18, // 22: centralconfig.v1.ConfigService.Subscribe:input_type -> centralconfig.v1.SubscribeRequest
	20, // 23: centralconfig.v1.ConfigService.ExportConfig:input_type -> centralconfig.v1.ExportConfigRequest
	22, // 24: centralconfig.v1.ConfigService.ImportConfig:input_type -> centralconfig.v1.ImportConfigRequest
	2,  // 25: centralconfig.v1.ConfigService.GetConfig:output_type -> centralconfig.v1.GetConfigResponse
	4,  // 26: centralconfig.v1.ConfigService.GetField:output_type -> centralconfig.v1.GetFieldResponse
	6,  // 27: centralconfig.v1.ConfigService.GetFields:output_type -> centralconfig.v1.GetFieldsResponse
	8,  // 28: centralconfig.v1.ConfigService.SetField:output_type -> centralconfig.v1.SetFieldResponse
	10, // 29: centralconfig.v1.ConfigService.SetFields:output_type -> centralconfig.v1.SetFieldsResponse
	13, // 30: centralconfig.v1.ConfigService.ListVersions:output_type -> centralconfig.v1.ListVersionsResponse
	15, // 31: centralconfig.v1.ConfigService.GetVersion:output_type -> centralconfig.v1.GetVersionResponse
	17, // 32: centralconfig.v1.ConfigService.RollbackToVersion:output_type -> centralconfig.v1.RollbackToVersionResponse
	19, // 33: centralconfig.v1.ConfigService.Subscribe:output_type -> centralconfig.v1.SubscribeResponse
	21, // 34: centralconfig.v1.ConfigService.ExportConfig:output_type -> centralconfig.v1.ExportConfigResponse
	23, // 35: centralconfig.v1.ConfigService.ImportConfig:output_type -> centralconfig.v1.ImportConfigResponse
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_centralconfig_v1_config_service_proto_init() }
func file_centralconfig_v1_config_service_proto_init() {
	if File_centralconfig_v1_config_service_proto != nil {
		return
	}
	file_centralconfig_v1_types_proto_init()
	file_centralconfig_v1_config_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_centralconfig_v1_config_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_centralconfig_v1_config_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_centralconfig_v1_config_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_centralconfig_v1_config_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_centralconfig_v1_config_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_centralconfig_v1_config_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_centralconfig_v1_config_service_proto_msgTypes[19].OneofWrappers = []any{}
	file_centralconfig_v1_config_service_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_centralconfig_v1_config_service_proto_rawDesc), len(file_centralconfig_v1_config_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_centralconfig_v1_config_service_proto_goTypes,
		DependencyIndexes: file_centralconfig_v1_config_service_proto_depIdxs,
		EnumInfos:         file_centralconfig_v1_config_service_proto_enumTypes,
		MessageInfos:      file_centralconfig_v1_config_service_proto_msgTypes,
	}.Build()
	File_centralconfig_v1_config_service_proto = out.File
	file_centralconfig_v1_config_service_proto_goTypes = nil
	file_centralconfig_v1_config_service_proto_depIdxs = nil
}
