// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: centralconfig/v1/schema_service.proto

package centralconfigv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchemaService_CreateSchema_FullMethodName   = "/centralconfig.v1.SchemaService/CreateSchema"
	SchemaService_GetSchema_FullMethodName      = "/centralconfig.v1.SchemaService/GetSchema"
	SchemaService_ListSchemas_FullMethodName    = "/centralconfig.v1.SchemaService/ListSchemas"
	SchemaService_UpdateSchema_FullMethodName   = "/centralconfig.v1.SchemaService/UpdateSchema"
	SchemaService_DeleteSchema_FullMethodName   = "/centralconfig.v1.SchemaService/DeleteSchema"
	SchemaService_PublishSchema_FullMethodName  = "/centralconfig.v1.SchemaService/PublishSchema"
	SchemaService_CreateTenant_FullMethodName   = "/centralconfig.v1.SchemaService/CreateTenant"
	SchemaService_GetTenant_FullMethodName      = "/centralconfig.v1.SchemaService/GetTenant"
	SchemaService_ListTenants_FullMethodName    = "/centralconfig.v1.SchemaService/ListTenants"
	SchemaService_UpdateTenant_FullMethodName   = "/centralconfig.v1.SchemaService/UpdateTenant"
	SchemaService_DeleteTenant_FullMethodName   = "/centralconfig.v1.SchemaService/DeleteTenant"
	SchemaService_LockField_FullMethodName      = "/centralconfig.v1.SchemaService/LockField"
	SchemaService_UnlockField_FullMethodName    = "/centralconfig.v1.SchemaService/UnlockField"
	SchemaService_ListFieldLocks_FullMethodName = "/centralconfig.v1.SchemaService/ListFieldLocks"
	SchemaService_ExportSchema_FullMethodName   = "/centralconfig.v1.SchemaService/ExportSchema"
	SchemaService_ImportSchema_FullMethodName   = "/centralconfig.v1.SchemaService/ImportSchema"
)

// SchemaServiceClient is the client API for SchemaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SchemaService manages configuration schemas, tenants, and field-level locking.
//
// Schemas define the allowed fields and their types for tenant configurations.
// Each schema is versioned — updates create new immutable versions that must be
// published before tenants can use them.
type SchemaServiceClient interface {
	// CreateSchema creates a new schema with an initial draft version (v1).
	CreateSchema(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error)
	// GetSchema retrieves a schema by ID, optionally at a specific version.
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// ListSchemas returns all schemas, ordered by creation time (newest first).
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	// UpdateSchema creates a new draft version by merging field changes with the latest version.
	UpdateSchema(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error)
	// DeleteSchema permanently deletes a schema and all its versions. Cascades to tenants.
	DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
	// PublishSchema marks a schema version as published and immutable.
	// Only published versions can be assigned to tenants.
	PublishSchema(ctx context.Context, in *PublishSchemaRequest, opts ...grpc.CallOption) (*PublishSchemaResponse, error)
	// CreateTenant creates a new tenant assigned to a published schema version.
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error)
	// GetTenant retrieves a tenant by ID.
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
	// ListTenants returns tenants, optionally filtered by schema.
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	// UpdateTenant updates a tenant's name or upgrades its schema version.
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*UpdateTenantResponse, error)
	// DeleteTenant permanently deletes a tenant and all its configuration data.
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error)
	// LockField prevents a field from being modified.
	LockField(ctx context.Context, in *LockFieldRequest, opts ...grpc.CallOption) (*LockFieldResponse, error)
	// UnlockField removes a field lock, allowing modifications again.
	UnlockField(ctx context.Context, in *UnlockFieldRequest, opts ...grpc.CallOption) (*UnlockFieldResponse, error)
	// ListFieldLocks returns all active field locks for a tenant.
	ListFieldLocks(ctx context.Context, in *ListFieldLocksRequest, opts ...grpc.CallOption) (*ListFieldLocksResponse, error)
	// ExportSchema serializes a schema version to YAML.
	ExportSchema(ctx context.Context, in *ExportSchemaRequest, opts ...grpc.CallOption) (*ExportSchemaResponse, error)
	// ImportSchema creates a schema (or new version) from YAML.
	// Full-replace semantics: the YAML defines the complete field set.
	// Returns AlreadyExists if the imported fields are identical to the latest version.
	ImportSchema(ctx context.Context, in *ImportSchemaRequest, opts ...grpc.CallOption) (*ImportSchemaResponse, error)
}

type schemaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchemaServiceClient(cc grpc.ClientConnInterface) SchemaServiceClient {
	return &schemaServiceClient{cc}
}

func (c *schemaServiceClient) CreateSchema(ctx context.Context, in *CreateSchemaRequest, opts ...grpc.CallOption) (*CreateSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_CreateSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, SchemaService_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) UpdateSchema(ctx context.Context, in *UpdateSchemaRequest, opts ...grpc.CallOption) (*UpdateSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_UpdateSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_DeleteSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) PublishSchema(ctx context.Context, in *PublishSchemaRequest, opts ...grpc.CallOption) (*PublishSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_PublishSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantResponse)
	err := c.cc.Invoke(ctx, SchemaService_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, SchemaService_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, SchemaService_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*UpdateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTenantResponse)
	err := c.cc.Invoke(ctx, SchemaService_UpdateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTenantResponse)
	err := c.cc.Invoke(ctx, SchemaService_DeleteTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) LockField(ctx context.Context, in *LockFieldRequest, opts ...grpc.CallOption) (*LockFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockFieldResponse)
	err := c.cc.Invoke(ctx, SchemaService_LockField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) UnlockField(ctx context.Context, in *UnlockFieldRequest, opts ...grpc.CallOption) (*UnlockFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockFieldResponse)
	err := c.cc.Invoke(ctx, SchemaService_UnlockField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) ListFieldLocks(ctx context.Context, in *ListFieldLocksRequest, opts ...grpc.CallOption) (*ListFieldLocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFieldLocksResponse)
	err := c.cc.Invoke(ctx, SchemaService_ListFieldLocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) ExportSchema(ctx context.Context, in *ExportSchemaRequest, opts ...grpc.CallOption) (*ExportSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_ExportSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schemaServiceClient) ImportSchema(ctx context.Context, in *ImportSchemaRequest, opts ...grpc.CallOption) (*ImportSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportSchemaResponse)
	err := c.cc.Invoke(ctx, SchemaService_ImportSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemaServiceServer is the server API for SchemaService service.
// All implementations must embed UnimplementedSchemaServiceServer
// for forward compatibility.
//
// SchemaService manages configuration schemas, tenants, and field-level locking.
//
// Schemas define the allowed fields and their types for tenant configurations.
// Each schema is versioned — updates create new immutable versions that must be
// published before tenants can use them.
type SchemaServiceServer interface {
	// CreateSchema creates a new schema with an initial draft version (v1).
	CreateSchema(context.Context, *CreateSchemaRequest) (*CreateSchemaResponse, error)
	// GetSchema retrieves a schema by ID, optionally at a specific version.
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// ListSchemas returns all schemas, ordered by creation time (newest first).
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	// UpdateSchema creates a new draft version by merging field changes with the latest version.
	UpdateSchema(context.Context, *UpdateSchemaRequest) (*UpdateSchemaResponse, error)
	// DeleteSchema permanently deletes a schema and all its versions. Cascades to tenants.
	DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
	// PublishSchema marks a schema version as published and immutable.
	// Only published versions can be assigned to tenants.
	PublishSchema(context.Context, *PublishSchemaRequest) (*PublishSchemaResponse, error)
	// CreateTenant creates a new tenant assigned to a published schema version.
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error)
	// GetTenant retrieves a tenant by ID.
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
	// ListTenants returns tenants, optionally filtered by schema.
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	// UpdateTenant updates a tenant's name or upgrades its schema version.
	UpdateTenant(context.Context, *UpdateTenantRequest) (*UpdateTenantResponse, error)
	// DeleteTenant permanently deletes a tenant and all its configuration data.
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error)
	// LockField prevents a field from being modified.
	LockField(context.Context, *LockFieldRequest) (*LockFieldResponse, error)
	// UnlockField removes a field lock, allowing modifications again.
	UnlockField(context.Context, *UnlockFieldRequest) (*UnlockFieldResponse, error)
	// ListFieldLocks returns all active field locks for a tenant.
	ListFieldLocks(context.Context, *ListFieldLocksRequest) (*ListFieldLocksResponse, error)
	// ExportSchema serializes a schema version to YAML.
	ExportSchema(context.Context, *ExportSchemaRequest) (*ExportSchemaResponse, error)
	// ImportSchema creates a schema (or new version) from YAML.
	// Full-replace semantics: the YAML defines the complete field set.
	// Returns AlreadyExists if the imported fields are identical to the latest version.
	ImportSchema(context.Context, *ImportSchemaRequest) (*ImportSchemaResponse, error)
	mustEmbedUnimplementedSchemaServiceServer()
}

// UnimplementedSchemaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchemaServiceServer struct{}

func (UnimplementedSchemaServiceServer) CreateSchema(context.Context, *CreateSchemaRequest) (*CreateSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSchema not implemented")
}
func (UnimplementedSchemaServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedSchemaServiceServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedSchemaServiceServer) UpdateSchema(context.Context, *UpdateSchemaRequest) (*UpdateSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSchema not implemented")
}
func (UnimplementedSchemaServiceServer) DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSchema not implemented")
}
func (UnimplementedSchemaServiceServer) PublishSchema(context.Context, *PublishSchemaRequest) (*PublishSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSchema not implemented")
}
func (UnimplementedSchemaServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedSchemaServiceServer) GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedSchemaServiceServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedSchemaServiceServer) UpdateTenant(context.Context, *UpdateTenantRequest) (*UpdateTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTenant not implemented")
}
func (UnimplementedSchemaServiceServer) DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedSchemaServiceServer) LockField(context.Context, *LockFieldRequest) (*LockFieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockField not implemented")
}
func (UnimplementedSchemaServiceServer) UnlockField(context.Context, *UnlockFieldRequest) (*UnlockFieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockField not implemented")
}
func (UnimplementedSchemaServiceServer) ListFieldLocks(context.Context, *ListFieldLocksRequest) (*ListFieldLocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFieldLocks not implemented")
}
func (UnimplementedSchemaServiceServer) ExportSchema(context.Context, *ExportSchemaRequest) (*ExportSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSchema not implemented")
}
func (UnimplementedSchemaServiceServer) ImportSchema(context.Context, *ImportSchemaRequest) (*ImportSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportSchema not implemented")
}
func (UnimplementedSchemaServiceServer) mustEmbedUnimplementedSchemaServiceServer() {}
func (UnimplementedSchemaServiceServer) testEmbeddedByValue()                       {}

// UnsafeSchemaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchemaServiceServer will
// result in compilation errors.
type UnsafeSchemaServiceServer interface {
	mustEmbedUnimplementedSchemaServiceServer()
}

func RegisterSchemaServiceServer(s grpc.ServiceRegistrar, srv SchemaServiceServer) {
	// If the following call panics, it indicates UnimplementedSchemaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchemaService_ServiceDesc, srv)
}

func _SchemaService_CreateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).CreateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_CreateSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).CreateSchema(ctx, req.(*CreateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_UpdateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).UpdateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_UpdateSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).UpdateSchema(ctx, req.(*UpdateSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_DeleteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).DeleteSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_DeleteSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).DeleteSchema(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_PublishSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).PublishSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_PublishSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).PublishSchema(ctx, req.(*PublishSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_UpdateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).UpdateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_UpdateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).UpdateTenant(ctx, req.(*UpdateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_LockField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).LockField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_LockField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).LockField(ctx, req.(*LockFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_UnlockField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).UnlockField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_UnlockField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).UnlockField(ctx, req.(*UnlockFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_ListFieldLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFieldLocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).ListFieldLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_ListFieldLocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).ListFieldLocks(ctx, req.(*ListFieldLocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_ExportSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).ExportSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_ExportSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).ExportSchema(ctx, req.(*ExportSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchemaService_ImportSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemaServiceServer).ImportSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchemaService_ImportSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemaServiceServer).ImportSchema(ctx, req.(*ImportSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchemaService_ServiceDesc is the grpc.ServiceDesc for SchemaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchemaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "centralconfig.v1.SchemaService",
	HandlerType: (*SchemaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSchema",
			Handler:    _SchemaService_CreateSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _SchemaService_GetSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _SchemaService_ListSchemas_Handler,
		},
		{
			MethodName: "UpdateSchema",
			Handler:    _SchemaService_UpdateSchema_Handler,
		},
		{
			MethodName: "DeleteSchema",
			Handler:    _SchemaService_DeleteSchema_Handler,
		},
		{
			MethodName: "PublishSchema",
			Handler:    _SchemaService_PublishSchema_Handler,
		},
		{
			MethodName: "CreateTenant",
			Handler:    _SchemaService_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _SchemaService_GetTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _SchemaService_ListTenants_Handler,
		},
		{
			MethodName: "UpdateTenant",
			Handler:    _SchemaService_UpdateTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _SchemaService_DeleteTenant_Handler,
		},
		{
			MethodName: "LockField",
			Handler:    _SchemaService_LockField_Handler,
		},
		{
			MethodName: "UnlockField",
			Handler:    _SchemaService_UnlockField_Handler,
		},
		{
			MethodName: "ListFieldLocks",
			Handler:    _SchemaService_ListFieldLocks_Handler,
		},
		{
			MethodName: "ExportSchema",
			Handler:    _SchemaService_ExportSchema_Handler,
		},
		{
			MethodName: "ImportSchema",
			Handler:    _SchemaService_ImportSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "centralconfig/v1/schema_service.proto",
}
