// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: centralconfig/v1/schema_service.proto

package centralconfigv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique name for the schema. Must be a valid slug: lowercase alphanumeric
	// and hyphens, 1-63 characters (e.g. "payment-config", "settlement-rules").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description of the schema's purpose.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Initial field definitions for version 1. At least one field is required.
	Fields        []*SchemaField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchemaRequest) Reset() {
	*x = CreateSchemaRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchemaRequest) ProtoMessage() {}

func (x *CreateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchemaRequest.ProtoReflect.Descriptor instead.
func (*CreateSchemaRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSchemaRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateSchemaRequest) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CreateSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created schema with version 1 (draft, unpublished).
	Schema        *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchemaResponse) Reset() {
	*x = CreateSchemaResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchemaResponse) ProtoMessage() {}

func (x *CreateSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchemaResponse.ProtoReflect.Descriptor instead.
func (*CreateSchemaResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSchemaResponse) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type GetSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Schema version to retrieve. If omitted, returns the latest version.
	Version       *int32 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSchemaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSchemaRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *Schema                `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSchemaResponse) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ListSchemasRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter schemas by name prefix. Currently reserved for future use.
	NameFilter *string `protobuf:"bytes,1,opt,name=name_filter,json=nameFilter,proto3,oneof" json:"name_filter,omitempty"`
	// Maximum number of results to return. Defaults to 50, max 100.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from a previous ListSchemasResponse.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListSchemasRequest) GetNameFilter() string {
	if x != nil && x.NameFilter != nil {
		return *x.NameFilter
	}
	return ""
}

func (x *ListSchemasRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSchemasRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSchemasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schemas with their latest version.
	Schemas []*Schema `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	// Token for the next page. Empty if no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListSchemasResponse) GetSchemas() []*Schema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *ListSchemasResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Description of what changed in this version.
	VersionDescription *string `protobuf:"bytes,2,opt,name=version_description,json=versionDescription,proto3,oneof" json:"version_description,omitempty"`
	// Fields to add or modify. Existing fields not listed here are carried
	// forward unchanged from the latest version.
	Fields []*SchemaField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Dot-separated paths of fields to remove from the new version.
	RemoveFields  []string `protobuf:"bytes,4,rep,name=remove_fields,json=removeFields,proto3" json:"remove_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchemaRequest) Reset() {
	*x = UpdateSchemaRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemaRequest) ProtoMessage() {}

func (x *UpdateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemaRequest.ProtoReflect.Descriptor instead.
func (*UpdateSchemaRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSchemaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSchemaRequest) GetVersionDescription() string {
	if x != nil && x.VersionDescription != nil {
		return *x.VersionDescription
	}
	return ""
}

func (x *UpdateSchemaRequest) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateSchemaRequest) GetRemoveFields() []string {
	if x != nil {
		return x.RemoveFields
	}
	return nil
}

type UpdateSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new schema version (draft, unpublished).
	Schema        *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSchemaResponse) Reset() {
	*x = UpdateSchemaResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemaResponse) ProtoMessage() {}

func (x *UpdateSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSchemaResponse.ProtoReflect.Descriptor instead.
func (*UpdateSchemaResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSchemaResponse) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type DeleteSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema ID (UUID). Cascades to all versions, fields, and associated tenants.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemaRequest) Reset() {
	*x = DeleteSchemaRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemaRequest) ProtoMessage() {}

func (x *DeleteSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemaRequest.ProtoReflect.Descriptor instead.
func (*DeleteSchemaRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSchemaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSchemaResponse) Reset() {
	*x = DeleteSchemaResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSchemaResponse) ProtoMessage() {}

func (x *DeleteSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSchemaResponse.ProtoReflect.Descriptor instead.
func (*DeleteSchemaResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{9}
}

type PublishSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The version number to publish. Must be an existing draft version.
	// Once published, the version is immutable.
	Version       int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSchemaRequest) Reset() {
	*x = PublishSchemaRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSchemaRequest) ProtoMessage() {}

func (x *PublishSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSchemaRequest.ProtoReflect.Descriptor instead.
func (*PublishSchemaRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{10}
}

func (x *PublishSchemaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishSchemaRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PublishSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The published schema version.
	Schema        *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSchemaResponse) Reset() {
	*x = PublishSchemaResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSchemaResponse) ProtoMessage() {}

func (x *PublishSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSchemaResponse.ProtoReflect.Descriptor instead.
func (*PublishSchemaResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{11}
}

func (x *PublishSchemaResponse) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type CreateTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique name for the tenant. Must be a valid slug: lowercase alphanumeric
	// and hyphens, 1-63 characters (e.g. "acme-corp", "tenant-42").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The schema to assign to this tenant (UUID).
	SchemaId string `protobuf:"bytes,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// The schema version to use. Must be a published version.
	SchemaVersion int32 `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *CreateTenantRequest) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type GetTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type ListTenantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by schema ID (UUID). If omitted, returns tenants across all schemas.
	SchemaId *string `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3,oneof" json:"schema_id,omitempty"`
	// Maximum number of results to return. Defaults to 50, max 100.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination token from a previous ListTenantsResponse.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListTenantsRequest) GetSchemaId() string {
	if x != nil && x.SchemaId != nil {
		return *x.SchemaId
	}
	return ""
}

func (x *ListTenantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTenantsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTenantsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Tenants []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	// Token for the next page. Empty if no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// New name for the tenant. Must be a valid slug if provided.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Upgrade to a new schema version. The new version must belong to the
	// same schema and must be published.
	SchemaVersion *int32 `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3,oneof" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTenantRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTenantRequest) GetSchemaVersion() int32 {
	if x != nil && x.SchemaVersion != nil {
		return *x.SchemaVersion
	}
	return 0
}

type UpdateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantResponse) Reset() {
	*x = UpdateTenantResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantResponse) ProtoMessage() {}

func (x *UpdateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type DeleteTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID). Cascades to all config versions, values, and field locks.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{21}
}

type LockFieldRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Dot-separated field path to lock (e.g. "payments.currency").
	FieldPath string `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// For enum fields: lock only these specific values. If empty, the
	// entire field is locked regardless of value.
	LockedValues  []string `protobuf:"bytes,3,rep,name=locked_values,json=lockedValues,proto3" json:"locked_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockFieldRequest) Reset() {
	*x = LockFieldRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockFieldRequest) ProtoMessage() {}

func (x *LockFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockFieldRequest.ProtoReflect.Descriptor instead.
func (*LockFieldRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{22}
}

func (x *LockFieldRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LockFieldRequest) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *LockFieldRequest) GetLockedValues() []string {
	if x != nil {
		return x.LockedValues
	}
	return nil
}

type LockFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockFieldResponse) Reset() {
	*x = LockFieldResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockFieldResponse) ProtoMessage() {}

func (x *LockFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockFieldResponse.ProtoReflect.Descriptor instead.
func (*LockFieldResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{23}
}

type UnlockFieldRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Dot-separated field path to unlock.
	FieldPath     string `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockFieldRequest) Reset() {
	*x = UnlockFieldRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockFieldRequest) ProtoMessage() {}

func (x *UnlockFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockFieldRequest.ProtoReflect.Descriptor instead.
func (*UnlockFieldRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{24}
}

func (x *UnlockFieldRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UnlockFieldRequest) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

type UnlockFieldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockFieldResponse) Reset() {
	*x = UnlockFieldResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockFieldResponse) ProtoMessage() {}

func (x *UnlockFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockFieldResponse.ProtoReflect.Descriptor instead.
func (*UnlockFieldResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{25}
}

type ListFieldLocksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (UUID).
	TenantId      string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFieldLocksRequest) Reset() {
	*x = ListFieldLocksRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFieldLocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFieldLocksRequest) ProtoMessage() {}

func (x *ListFieldLocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFieldLocksRequest.ProtoReflect.Descriptor instead.
func (*ListFieldLocksRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{26}
}

func (x *ListFieldLocksRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListFieldLocksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All active field locks for the tenant.
	Locks         []*FieldLock `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFieldLocksResponse) Reset() {
	*x = ListFieldLocksResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFieldLocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFieldLocksResponse) ProtoMessage() {}

func (x *ListFieldLocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFieldLocksResponse.ProtoReflect.Descriptor instead.
func (*ListFieldLocksResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{27}
}

func (x *ListFieldLocksResponse) GetLocks() []*FieldLock {
	if x != nil {
		return x.Locks
	}
	return nil
}

type ExportSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema ID (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Schema version to export. If omitted, exports the latest version.
	Version       *int32 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSchemaRequest) Reset() {
	*x = ExportSchemaRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSchemaRequest) ProtoMessage() {}

func (x *ExportSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSchemaRequest.ProtoReflect.Descriptor instead.
func (*ExportSchemaRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{28}
}

func (x *ExportSchemaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportSchemaRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type ExportSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// YAML-encoded schema (syntax v1). Includes schema name, description,
	// version, and all field definitions with OAS-style constraint naming.
	// Server-generated fields (id, checksum, published, created_at) are excluded.
	YamlContent   []byte `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSchemaResponse) Reset() {
	*x = ExportSchemaResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSchemaResponse) ProtoMessage() {}

func (x *ExportSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSchemaResponse.ProtoReflect.Descriptor instead.
func (*ExportSchemaResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{29}
}

func (x *ExportSchemaResponse) GetYamlContent() []byte {
	if x != nil {
		return x.YamlContent
	}
	return nil
}

type ImportSchemaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// YAML-encoded schema (syntax v1). Must include `syntax`, `name`, and `fields`.
	//
	// Import uses full-replace semantics:
	// - If no schema with this name exists: creates a new schema with version 1.
	// - If a schema exists and fields differ from latest: creates the next version.
	// - If a schema exists and fields are identical: returns AlreadyExists error.
	//
	// Imported versions are created as drafts (unpublished) unless auto_publish is true.
	// The `version` field in the YAML is informational — the server assigns
	// the next version number automatically.
	YamlContent []byte `protobuf:"bytes,1,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content,omitempty"`
	// When true, the imported version is automatically published after creation.
	// If the schema already exists and fields are identical (AlreadyExists), this has no effect.
	AutoPublish   bool `protobuf:"varint,2,opt,name=auto_publish,json=autoPublish,proto3" json:"auto_publish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSchemaRequest) Reset() {
	*x = ImportSchemaRequest{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSchemaRequest) ProtoMessage() {}

func (x *ImportSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSchemaRequest.ProtoReflect.Descriptor instead.
func (*ImportSchemaRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{30}
}

func (x *ImportSchemaRequest) GetYamlContent() []byte {
	if x != nil {
		return x.YamlContent
	}
	return nil
}

func (x *ImportSchemaRequest) GetAutoPublish() bool {
	if x != nil {
		return x.AutoPublish
	}
	return false
}

type ImportSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created (or existing, on AlreadyExists) schema version.
	Schema        *Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSchemaResponse) Reset() {
	*x = ImportSchemaResponse{}
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSchemaResponse) ProtoMessage() {}

func (x *ImportSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_schema_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSchemaResponse.ProtoReflect.Descriptor instead.
func (*ImportSchemaResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_schema_service_proto_rawDescGZIP(), []int{31}
}

func (x *ImportSchemaResponse) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

var File_centralconfig_v1_schema_service_proto protoreflect.FileDescriptor

const file_centralconfig_v1_schema_service_proto_rawDesc = "" +
	"\n" +
	"%centralconfig/v1/schema_service.proto\x12\x10centralconfig.v1\x1a\x1ccentralconfig/v1/types.proto\x1a\x1cgoogle/api/annotations.proto\"\x97\x01\n" +
	"\x13CreateSchemaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x125\n" +
	"\x06fields\x18\x03 \x03(\v2\x1d.centralconfig.v1.SchemaFieldR\x06fieldsB\x0e\n" +
	"\f_description\"H\n" +
	"\x14CreateSchemaResponse\x120\n" +
	"\x06schema\x18\x01 \x01(\v2\x18.centralconfig.v1.SchemaR\x06schema\"M\n" +
	"\x10GetSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\x05H\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"E\n" +
	"\x11GetSchemaResponse\x120\n" +
	"\x06schema\x18\x01 \x01(\v2\x18.centralconfig.v1.SchemaR\x06schema\"\x86\x01\n" +
	"\x12ListSchemasRequest\x12$\n" +
	"\vname_filter\x18\x01 \x01(\tH\x00R\n" +
	"nameFilter\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageTokenB\x0e\n" +
	"\f_name_filter\"q\n" +
	"\x13ListSchemasResponse\x122\n" +
	"\aschemas\x18\x01 \x03(\v2\x18.centralconfig.v1.SchemaR\aschemas\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xcf\x01\n" +
	"\x13UpdateSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x13version_description\x18\x02 \x01(\tH\x00R\x12versionDescription\x88\x01\x01\x125\n" +
	"\x06fields\x18\x03 \x03(\v2\x1d.centralconfig.v1.SchemaFieldR\x06fields\x12#\n" +
	"\rremove_fields\x18\x04 \x03(\tR\fremoveFieldsB\x16\n" +
	"\x14_version_description\"H\n" +
	"\x14UpdateSchemaResponse\x120\n" +
	"\x06schema\x18\x01 \x01(\v2\x18.centralconfig.v1.SchemaR\x06schema\"%\n" +
	"\x13DeleteSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSchemaResponse\"@\n" +
	"\x14PublishSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"I\n" +
	"\x15PublishSchemaResponse\x120\n" +
	"\x06schema\x18\x01 \x01(\v2\x18.centralconfig.v1.SchemaR\x06schema\"m\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tschema_id\x18\x02 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x05R\rschemaVersion\"H\n" +
	"\x14CreateTenantResponse\x120\n" +
	"\x06tenant\x18\x01 \x01(\v2\x18.centralconfig.v1.TenantR\x06tenant\"\"\n" +
	"\x10GetTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x11GetTenantResponse\x120\n" +
	"\x06tenant\x18\x01 \x01(\v2\x18.centralconfig.v1.TenantR\x06tenant\"\x80\x01\n" +
	"\x12ListTenantsRequest\x12 \n" +
	"\tschema_id\x18\x01 \x01(\tH\x00R\bschemaId\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageTokenB\f\n" +
	"\n" +
	"_schema_id\"q\n" +
	"\x13ListTenantsResponse\x122\n" +
	"\atenants\x18\x01 \x03(\v2\x18.centralconfig.v1.TenantR\atenants\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x86\x01\n" +
	"\x13UpdateTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12*\n" +
	"\x0eschema_version\x18\x03 \x01(\x05H\x01R\rschemaVersion\x88\x01\x01B\a\n" +
	"\x05_nameB\x11\n" +
	"\x0f_schema_version\"H\n" +
	"\x14UpdateTenantResponse\x120\n" +
	"\x06tenant\x18\x01 \x01(\v2\x18.centralconfig.v1.TenantR\x06tenant\"%\n" +
	"\x13DeleteTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteTenantResponse\"s\n" +
	"\x10LockFieldRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\x12#\n" +
	"\rlocked_values\x18\x03 \x03(\tR\flockedValues\"\x13\n" +
	"\x11LockFieldResponse\"P\n" +
	"\x12UnlockFieldRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\"\x15\n" +
	"\x13UnlockFieldResponse\"4\n" +
	"\x15ListFieldLocksRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"K\n" +
	"\x16ListFieldLocksResponse\x121\n" +
	"\x05locks\x18\x01 \x03(\v2\x1b.centralconfig.v1.FieldLockR\x05locks\"P\n" +
	"\x13ExportSchemaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\aversion\x18\x02 \x01(\x05H\x00R\aversion\x88\x01\x01B\n" +
	"\n" +
	"\b_version\"9\n" +
	"\x14ExportSchemaResponse\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\fR\vyamlContent\"[\n" +
	"\x13ImportSchemaRequest\x12!\n" +
	"\fyaml_content\x18\x01 \x01(\fR\vyamlContent\x12!\n" +
	"\fauto_publish\x18\x02 \x01(\bR\vautoPublish\"H\n" +
	"\x14ImportSchemaResponse\x120\n" +
	"\x06schema\x18\x01 \x01(\v2\x18.centralconfig.v1.SchemaR\x06schema2\xcd\x0f\n" +
	"\rSchemaService\x12u\n" +
	"\fCreateSchema\x12%.centralconfig.v1.CreateSchemaRequest\x1a&.centralconfig.v1.CreateSchemaResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/schemas\x12n\n" +
	"\tGetSchema\x12\".centralconfig.v1.GetSchemaRequest\x1a#.centralconfig.v1.GetSchemaResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/schemas/{id}\x12o\n" +
	"\vListSchemas\x12$.centralconfig.v1.ListSchemasRequest\x1a%.centralconfig.v1.ListSchemasResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/schemas\x12z\n" +
	"\fUpdateSchema\x12%.centralconfig.v1.UpdateSchemaRequest\x1a&.centralconfig.v1.UpdateSchemaResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*2\x10/v1/schemas/{id}\x12w\n" +
	"\fDeleteSchema\x12%.centralconfig.v1.DeleteSchemaRequest\x1a&.centralconfig.v1.DeleteSchemaResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/schemas/{id}\x12\x85\x01\n" +
	"\rPublishSchema\x12&.centralconfig.v1.PublishSchemaRequest\x1a'.centralconfig.v1.PublishSchemaResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/schemas/{id}/publish\x12u\n" +
	"\fCreateTenant\x12%.centralconfig.v1.CreateTenantRequest\x1a&.centralconfig.v1.CreateTenantResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/tenants\x12n\n" +
	"\tGetTenant\x12\".centralconfig.v1.GetTenantRequest\x1a#.centralconfig.v1.GetTenantResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/tenants/{id}\x12o\n" +
	"\vListTenants\x12$.centralconfig.v1.ListTenantsRequest\x1a%.centralconfig.v1.ListTenantsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/tenants\x12z\n" +
	"\fUpdateTenant\x12%.centralconfig.v1.UpdateTenantRequest\x1a&.centralconfig.v1.UpdateTenantResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*2\x10/v1/tenants/{id}\x12w\n" +
	"\fDeleteTenant\x12%.centralconfig.v1.DeleteTenantRequest\x1a&.centralconfig.v1.DeleteTenantResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/tenants/{id}\x12~\n" +
	"\tLockField\x12\".centralconfig.v1.LockFieldRequest\x1a#.centralconfig.v1.LockFieldResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/tenants/{tenant_id}/locks\x12\x8e\x01\n" +
	"\vUnlockField\x12$.centralconfig.v1.UnlockFieldRequest\x1a%.centralconfig.v1.UnlockFieldResponse\"2\x82\xd3\xe4\x93\x02,**/v1/tenants/{tenant_id}/locks/{field_path}\x12\x8a\x01\n" +
	"\x0eListFieldLocks\x12'.centralconfig.v1.ListFieldLocksRequest\x1a(.centralconfig.v1.ListFieldLocksResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/tenants/{tenant_id}/locks\x12~\n" +
	"\fExportSchema\x12%.centralconfig.v1.ExportSchemaRequest\x1a&.centralconfig.v1.ExportSchemaResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/schemas/{id}/export\x12|\n" +
	"\fImportSchema\x12%.centralconfig.v1.ImportSchemaRequest\x1a&.centralconfig.v1.ImportSchemaResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/schemas/importB\xca\x01\n" +
	"\x14com.centralconfig.v1B\x12SchemaServiceProtoP\x01Z=github.com/zeevdr/decree/api/centralconfig/v1;centralconfigv1\xa2\x02\x03CXX\xaa\x02\x10Centralconfig.V1\xca\x02\x10Centralconfig\\V1\xe2\x02\x1cCentralconfig\\V1\\GPBMetadata\xea\x02\x11Centralconfig::V1b\x06proto3"

var (
	file_centralconfig_v1_schema_service_proto_rawDescOnce sync.Once
	file_centralconfig_v1_schema_service_proto_rawDescData []byte
)

func file_centralconfig_v1_schema_service_proto_rawDescGZIP() []byte {
	file_centralconfig_v1_schema_service_proto_rawDescOnce.Do(func() {
		file_centralconfig_v1_schema_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_centralconfig_v1_schema_service_proto_rawDesc), len(file_centralconfig_v1_schema_service_proto_rawDesc)))
	})
	return file_centralconfig_v1_schema_service_proto_rawDescData
}

var file_centralconfig_v1_schema_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_centralconfig_v1_schema_service_proto_goTypes = []any{
	(*CreateSchemaRequest)(nil),    // 0: centralconfig.v1.CreateSchemaRequest
	(*CreateSchemaResponse)(nil),   // 1: centralconfig.v1.CreateSchemaResponse
	(*GetSchemaRequest)(nil),       // 2: centralconfig.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil),      // 3: centralconfig.v1.GetSchemaResponse
	(*ListSchemasRequest)(nil),     // 4: centralconfig.v1.ListSchemasRequest
	(*ListSchemasResponse)(nil),    // 5: centralconfig.v1.ListSchemasResponse
	(*UpdateSchemaRequest)(nil),    // 6: centralconfig.v1.UpdateSchemaRequest
	(*UpdateSchemaResponse)(nil),   // 7: centralconfig.v1.UpdateSchemaResponse
	(*DeleteSchemaRequest)(nil),    // 8: centralconfig.v1.DeleteSchemaRequest
	(*DeleteSchemaResponse)(nil),   // 9: centralconfig.v1.DeleteSchemaResponse
	(*PublishSchemaRequest)(nil),   // 10: centralconfig.v1.PublishSchemaRequest
	(*PublishSchemaResponse)(nil),  // 11: centralconfig.v1.PublishSchemaResponse
	(*CreateTenantRequest)(nil),    // 12: centralconfig.v1.CreateTenantRequest
	(*CreateTenantResponse)(nil),   // 13: centralconfig.v1.CreateTenantResponse
	(*GetTenantRequest)(nil),       // 14: centralconfig.v1.GetTenantRequest
	(*GetTenantResponse)(nil),      // 15: centralconfig.v1.GetTenantResponse
	(*ListTenantsRequest)(nil),     // 16: centralconfig.v1.ListTenantsRequest
	(*ListTenantsResponse)(nil),    // 17: centralconfig.v1.ListTenantsResponse
	(*UpdateTenantRequest)(nil),    // 18: centralconfig.v1.UpdateTenantRequest
	(*UpdateTenantResponse)(nil),   // 19: centralconfig.v1.UpdateTenantResponse
	(*DeleteTenantRequest)(nil),    // 20: centralconfig.v1.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),   // 21: centralconfig.v1.DeleteTenantResponse
	(*LockFieldRequest)(nil),       // 22: centralconfig.v1.LockFieldRequest
	(*LockFieldResponse)(nil),      // 23: centralconfig.v1.LockFieldResponse
	(*UnlockFieldRequest)(nil),     // 24: centralconfig.v1.UnlockFieldRequest
	(*UnlockFieldResponse)(nil),    // 25: centralconfig.v1.UnlockFieldResponse
	(*ListFieldLocksRequest)(nil),  // 26: centralconfig.v1.ListFieldLocksRequest
	(*ListFieldLocksResponse)(nil), // 27: centralconfig.v1.ListFieldLocksResponse
	(*ExportSchemaRequest)(nil),    // 28: centralconfig.v1.ExportSchemaRequest
	(*ExportSchemaResponse)(nil),   // 29: centralconfig.v1.ExportSchemaResponse
	(*ImportSchemaRequest)(nil),    // 30: centralconfig.v1.ImportSchemaRequest
	(*ImportSchemaResponse)(nil),   // 31: centralconfig.v1.ImportSchemaResponse
	(*SchemaField)(nil),            // 32: centralconfig.v1.SchemaField
	(*Schema)(nil),                 // 33: centralconfig.v1.Schema
	(*Tenant)(nil),                 // 34: centralconfig.v1.Tenant
	(*FieldLock)(nil),              // 35: centralconfig.v1.FieldLock
}
var file_centralconfig_v1_schema_service_proto_depIdxs = []int32{
	32, // 0: centralconfig.v1.CreateSchemaRequest.fields:type_name -> centralconfig.v1.SchemaField
	33, // 1: centralconfig.v1.CreateSchemaResponse.schema:type_name -> centralconfig.v1.Schema
	33, // 2: centralconfig.v1.GetSchemaResponse.schema:type_name -> centralconfig.v1.Schema
	33, // 3: centralconfig.v1.ListSchemasResponse.schemas:type_name -> centralconfig.v1.Schema
	32, // 4: centralconfig.v1.UpdateSchemaRequest.fields:type_name -> centralconfig.v1.SchemaField
	33, // 5: centralconfig.v1.UpdateSchemaResponse.schema:type_name -> centralconfig.v1.Schema
	33, // 6: centralconfig.v1.PublishSchemaResponse.schema:type_name -> centralconfig.v1.Schema
	34, // 7: centralconfig.v1.CreateTenantResponse.tenant:type_name -> centralconfig.v1.Tenant
	34, // 8: centralconfig.v1.GetTenantResponse.tenant:type_name -> centralconfig.v1.Tenant
	34, // 9: centralconfig.v1.ListTenantsResponse.tenants:type_name -> centralconfig.v1.Tenant
	34, // 10: centralconfig.v1.UpdateTenantResponse.tenant:type_name -> centralconfig.v1.Tenant
	35, // 11: centralconfig.v1.ListFieldLocksResponse.locks:type_name -> centralconfig.v1.FieldLock
	33, // 12: centralconfig.v1.ImportSchemaResponse.schema:type_name -> centralconfig.v1.Schema
	0,  // 13: centralconfig.v1.SchemaService.CreateSchema:input_type -> centralconfig.v1.CreateSchemaRequest
	2,  // 14: centralconfig.v1.SchemaService.GetSchema:input_type -> centralconfig.v1.GetSchemaRequest
	4,  // 15: centralconfig.v1.SchemaService.ListSchemas:input_type -> centralconfig.v1.ListSchemasRequest
	6,  // 16: centralconfig.v1.SchemaService.UpdateSchema:input_type -> centralconfig.v1.UpdateSchemaRequest
	8,  // 17: centralconfig.v1.SchemaService.DeleteSchema:input_type -> centralconfig.v1.DeleteSchemaRequest
	10, // 18: centralconfig.v1.SchemaService.PublishSchema:input_type -> centralconfig.v1.PublishSchemaRequest
	12, // 19: centralconfig.v1.SchemaService.CreateTenant:input_type -> centralconfig.v1.CreateTenantRequest
	14, // 20: centralconfig.v1.SchemaService.GetTenant:input_type -> centralconfig.v1.GetTenantRequest
	16, // 21: centralconfig.v1.SchemaService.ListTenants:input_type -> centralconfig.v1.ListTenantsRequest
	18, // 22: centralconfig.v1.SchemaService.UpdateTenant:input_type -> centralconfig.v1.UpdateTenantRequest
	20, // 23: centralconfig.v1.SchemaService.DeleteTenant:input_type -> centralconfig.v1.DeleteTenantRequest
	22, // 24: centralconfig.v1.SchemaService.LockField:input_type -> centralconfig.v1.LockFieldRequest
	24, // 25: centralconfig.v1.SchemaService.UnlockField:input_type -> centralconfig.v1.UnlockFieldRequest
	26, // 26: centralconfig.v1.SchemaService.ListFieldLocks:input_type -> centralconfig.v1.ListFieldLocksRequest
	28, // 27: centralconfig.v1.SchemaService.ExportSchema:input_type -> centralconfig.v1.ExportSchemaRequest
	30, // 28: centralconfig.v1.SchemaService.ImportSchema:input_type -> centralconfig.v1.ImportSchemaRequest
	1,  // 29: centralconfig.v1.SchemaService.CreateSchema:output_type -> centralconfig.v1.CreateSchemaResponse
	3,  // 30: centralconfig.v1.SchemaService.GetSchema:output_type -> centralconfig.v1.GetSchemaResponse
	5,  // 31: centralconfig.v1.SchemaService.ListSchemas:output_type -> centralconfig.v1.ListSchemasResponse
	7,  // 32: centralconfig.v1.SchemaService.UpdateSchema:output_type -> centralconfig.v1.UpdateSchemaResponse
	9,  // 33: centralconfig.v1.SchemaService.DeleteSchema:output_type -> centralconfig.v1.DeleteSchemaResponse
	11, // 34: centralconfig.v1.SchemaService.PublishSchema:output_type -> centralconfig.v1.PublishSchemaResponse
	13, // 35: centralconfig.v1.SchemaService.CreateTenant:output_type -> centralconfig.v1.CreateTenantResponse
	15, // 36: centralconfig.v1.SchemaService.GetTenant:output_type -> centralconfig.v1.GetTenantResponse
	17, // 37: centralconfig.v1.SchemaService.ListTenants:output_type -> centralconfig.v1.ListTenantsResponse
	19, // 38: centralconfig.v1.SchemaService.UpdateTenant:output_type -> centralconfig.v1.UpdateTenantResponse
	21, // 39: centralconfig.v1.SchemaService.DeleteTenant:output_type -> centralconfig.v1.DeleteTenantResponse
	23, // 40: centralconfig.v1.SchemaService.LockField:output_type -> centralconfig.v1.LockFieldResponse
	25, // 41: centralconfig.v1.SchemaService.UnlockField:output_type -> centralconfig.v1.UnlockFieldResponse
	27, // 42: centralconfig.v1.SchemaService.ListFieldLocks:output_type -> centralconfig.v1.ListFieldLocksResponse
	29, // 43: centralconfig.v1.SchemaService.ExportSchema:output_type -> centralconfig.v1.ExportSchemaResponse
	31, // 44: centralconfig.v1.SchemaService.ImportSchema:output_type -> centralconfig.v1.ImportSchemaResponse
	29, // [29:45] is the sub-list for method output_type
	13, // [13:29] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_centralconfig_v1_schema_service_proto_init() }
func file_centralconfig_v1_schema_service_proto_init() {
	if File_centralconfig_v1_schema_service_proto != nil {
		return
	}
	file_centralconfig_v1_types_proto_init()
	file_centralconfig_v1_schema_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_centralconfig_v1_schema_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_centralconfig_v1_schema_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_centralconfig_v1_schema_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_centralconfig_v1_schema_service_proto_msgTypes[16].OneofWrappers = []any{}
	file_centralconfig_v1_schema_service_proto_msgTypes[18].OneofWrappers = []any{}
	file_centralconfig_v1_schema_service_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_centralconfig_v1_schema_service_proto_rawDesc), len(file_centralconfig_v1_schema_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_centralconfig_v1_schema_service_proto_goTypes,
		DependencyIndexes: file_centralconfig_v1_schema_service_proto_depIdxs,
		MessageInfos:      file_centralconfig_v1_schema_service_proto_msgTypes,
	}.Build()
	File_centralconfig_v1_schema_service_proto = out.File
	file_centralconfig_v1_schema_service_proto_goTypes = nil
	file_centralconfig_v1_schema_service_proto_depIdxs = nil
}
