// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: centralconfig/v1/types.proto

package centralconfigv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldType enumerates the supported configuration value types.
// Each type maps to a specific field in the TypedValue oneof.
type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	// Integer value. Encoded as a decimal string (e.g. "42", "-1").
	// Supports minimum/maximum constraints on the numeric value.
	FieldType_FIELD_TYPE_INT FieldType = 1
	// Free-form string value.
	// Supports minimum/maximum constraints on string length, pattern (regex),
	// and enum constraints.
	FieldType_FIELD_TYPE_STRING FieldType = 2
	// Timestamp value. Encoded as an RFC 3339 string (e.g. "2025-01-15T09:30:00Z").
	FieldType_FIELD_TYPE_TIME FieldType = 3
	// Duration value. Encoded as a Go-style duration string (e.g. "24h", "30m", "500ms").
	// Supports minimum/maximum constraints on the duration in seconds.
	FieldType_FIELD_TYPE_DURATION FieldType = 4
	// URL value. Must be a valid absolute URL.
	FieldType_FIELD_TYPE_URL FieldType = 5
	// JSON value. Stored as a JSON-encoded string.
	// Supports json_schema constraint for structural validation.
	FieldType_FIELD_TYPE_JSON FieldType = 6
	// Floating-point number value. Encoded as a decimal string (e.g. "3.14", "0.025").
	// Supports minimum/maximum constraints on the numeric value.
	FieldType_FIELD_TYPE_NUMBER FieldType = 7
	// Boolean value. Encoded as "true" or "false".
	FieldType_FIELD_TYPE_BOOL FieldType = 8
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_INT",
		2: "FIELD_TYPE_STRING",
		3: "FIELD_TYPE_TIME",
		4: "FIELD_TYPE_DURATION",
		5: "FIELD_TYPE_URL",
		6: "FIELD_TYPE_JSON",
		7: "FIELD_TYPE_NUMBER",
		8: "FIELD_TYPE_BOOL",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_INT":         1,
		"FIELD_TYPE_STRING":      2,
		"FIELD_TYPE_TIME":        3,
		"FIELD_TYPE_DURATION":    4,
		"FIELD_TYPE_URL":         5,
		"FIELD_TYPE_JSON":        6,
		"FIELD_TYPE_NUMBER":      7,
		"FIELD_TYPE_BOOL":        8,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_centralconfig_v1_types_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_centralconfig_v1_types_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{0}
}

// FieldConstraints defines validation rules for a schema field.
// Which constraints apply depends on the field's type — see FieldType docs.
type FieldConstraints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For integer/number/duration: minimum allowed value (inclusive, >=).
	Min *float64 `protobuf:"fixed64,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	// For integer/number/duration: maximum allowed value (inclusive, <=).
	Max *float64 `protobuf:"fixed64,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	// Regular expression pattern the value must match.
	// Applies to string-typed fields. Uses RE2 syntax.
	Regex *string `protobuf:"bytes,3,opt,name=regex,proto3,oneof" json:"regex,omitempty"`
	// Allowed values. If non-empty, the value must be one of these.
	// Applies to any field type.
	EnumValues []string `protobuf:"bytes,4,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	// JSON Schema document for structural validation of json-typed fields.
	// Encoded as a JSON string.
	JsonSchema *string `protobuf:"bytes,5,opt,name=json_schema,json=jsonSchema,proto3,oneof" json:"json_schema,omitempty"`
	// For integer/number/duration: exclusive minimum (strict, >).
	ExclusiveMin *float64 `protobuf:"fixed64,6,opt,name=exclusive_min,json=exclusiveMin,proto3,oneof" json:"exclusive_min,omitempty"`
	// For integer/number/duration: exclusive maximum (strict, <).
	ExclusiveMax *float64 `protobuf:"fixed64,7,opt,name=exclusive_max,json=exclusiveMax,proto3,oneof" json:"exclusive_max,omitempty"`
	// For string: minimum allowed length.
	MinLength *int32 `protobuf:"varint,8,opt,name=min_length,json=minLength,proto3,oneof" json:"min_length,omitempty"`
	// For string: maximum allowed length.
	MaxLength     *int32 `protobuf:"varint,9,opt,name=max_length,json=maxLength,proto3,oneof" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldConstraints) Reset() {
	*x = FieldConstraints{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConstraints) ProtoMessage() {}

func (x *FieldConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConstraints.ProtoReflect.Descriptor instead.
func (*FieldConstraints) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *FieldConstraints) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *FieldConstraints) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *FieldConstraints) GetRegex() string {
	if x != nil && x.Regex != nil {
		return *x.Regex
	}
	return ""
}

func (x *FieldConstraints) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *FieldConstraints) GetJsonSchema() string {
	if x != nil && x.JsonSchema != nil {
		return *x.JsonSchema
	}
	return ""
}

func (x *FieldConstraints) GetExclusiveMin() float64 {
	if x != nil && x.ExclusiveMin != nil {
		return *x.ExclusiveMin
	}
	return 0
}

func (x *FieldConstraints) GetExclusiveMax() float64 {
	if x != nil && x.ExclusiveMax != nil {
		return *x.ExclusiveMax
	}
	return 0
}

func (x *FieldConstraints) GetMinLength() int32 {
	if x != nil && x.MinLength != nil {
		return *x.MinLength
	}
	return 0
}

func (x *FieldConstraints) GetMaxLength() int32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

// SchemaField defines a single field within a configuration schema.
type SchemaField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dot-separated hierarchical path (e.g. "payments.settlement.window").
	// Must be unique within a schema version.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The value type for this field. Controls validation behavior.
	Type FieldType `protobuf:"varint,2,opt,name=type,proto3,enum=centralconfig.v1.FieldType" json:"type,omitempty"`
	// Validation constraints. Optional — when absent, any value of the
	// correct type is accepted.
	Constraints *FieldConstraints `protobuf:"bytes,3,opt,name=constraints,proto3" json:"constraints,omitempty"`
	// Whether this field accepts empty/null values.
	Nullable bool `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// Whether this field is deprecated. Deprecated fields are still readable
	// but clients should migrate to redirect_to if set.
	Deprecated bool `protobuf:"varint,5,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// When deprecated, reads of this field can be redirected to this path.
	RedirectTo *string `protobuf:"bytes,6,opt,name=redirect_to,json=redirectTo,proto3,oneof" json:"redirect_to,omitempty"`
	// Default value for this field, encoded as a string matching the field type.
	DefaultValue *string `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	// Human-readable description of the field's purpose.
	Description   *string `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaField) Reset() {
	*x = SchemaField{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaField) ProtoMessage() {}

func (x *SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaField.ProtoReflect.Descriptor instead.
func (*SchemaField) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *SchemaField) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SchemaField) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *SchemaField) GetConstraints() *FieldConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *SchemaField) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *SchemaField) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *SchemaField) GetRedirectTo() string {
	if x != nil && x.RedirectTo != nil {
		return *x.RedirectTo
	}
	return ""
}

func (x *SchemaField) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *SchemaField) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// Schema represents a configuration schema template.
// Schemas define the allowed fields and their types for tenant configurations.
// Each schema is versioned — updates create new immutable versions.
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned unique identifier (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique name for this schema. Must be a valid slug: lowercase alphanumeric
	// characters and hyphens, 1-63 characters, matching [a-z0-9]([a-z0-9-]*[a-z0-9])?.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description of the schema's purpose.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Schema version number (monotonically increasing, starting at 1).
	Version int32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// The version this was derived from. Absent for the initial version (v1).
	ParentVersion *int32 `protobuf:"varint,5,opt,name=parent_version,json=parentVersion,proto3,oneof" json:"parent_version,omitempty"`
	// Description of what changed in this version.
	VersionDescription string `protobuf:"bytes,6,opt,name=version_description,json=versionDescription,proto3" json:"version_description,omitempty"`
	// Deterministic checksum of the field definitions (type, constraints, path).
	// Used for change detection on import.
	Checksum string `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Whether this version is published. Only published versions can be
	// assigned to tenants. Published versions are immutable.
	Published bool `protobuf:"varint,8,opt,name=published,proto3" json:"published,omitempty"`
	// The fields defined in this schema version.
	Fields []*SchemaField `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`
	// When this version was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Schema) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Schema) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Schema) GetParentVersion() int32 {
	if x != nil && x.ParentVersion != nil {
		return *x.ParentVersion
	}
	return 0
}

func (x *Schema) GetVersionDescription() string {
	if x != nil {
		return x.VersionDescription
	}
	return ""
}

func (x *Schema) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Schema) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *Schema) GetFields() []*SchemaField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Schema) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Tenant represents an organization or entity that has its own configuration
// based on an assigned schema version.
type Tenant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned unique identifier (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique name for this tenant. Must be a valid slug: lowercase alphanumeric
	// characters and hyphens, 1-63 characters, matching [a-z0-9]([a-z0-9-]*[a-z0-9])?.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The schema this tenant's configuration is based on (UUID).
	SchemaId string `protobuf:"bytes,3,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// The specific schema version assigned to this tenant.
	// Must reference a published schema version.
	SchemaVersion int32 `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// When the tenant was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the tenant was last updated (name or schema version change).
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *Tenant) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tenant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// FieldLock prevents a configuration field from being modified by non-superadmin users.
// Superadmins bypass all field locks.
type FieldLock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant this lock applies to (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The dot-separated field path that is locked.
	FieldPath string `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// For enum fields: the specific subset of values that are locked
	// (not editable by admin). If empty, the entire field is locked.
	LockedValues  []string `protobuf:"bytes,3,rep,name=locked_values,json=lockedValues,proto3" json:"locked_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldLock) Reset() {
	*x = FieldLock{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldLock) ProtoMessage() {}

func (x *FieldLock) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldLock.ProtoReflect.Descriptor instead.
func (*FieldLock) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *FieldLock) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FieldLock) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *FieldLock) GetLockedValues() []string {
	if x != nil {
		return x.LockedValues
	}
	return nil
}

// TypedValue holds a configuration value with its native type.
// An unset oneof (no field present) represents a null value.
type TypedValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TypedValue_IntegerValue
	//	*TypedValue_NumberValue
	//	*TypedValue_StringValue
	//	*TypedValue_BoolValue
	//	*TypedValue_TimeValue
	//	*TypedValue_DurationValue
	//	*TypedValue_UrlValue
	//	*TypedValue_JsonValue
	Kind          isTypedValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedValue) Reset() {
	*x = TypedValue{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedValue) ProtoMessage() {}

func (x *TypedValue) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedValue.ProtoReflect.Descriptor instead.
func (*TypedValue) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *TypedValue) GetKind() isTypedValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TypedValue) GetIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*TypedValue_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *TypedValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*TypedValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *TypedValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*TypedValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *TypedValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*TypedValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *TypedValue) GetTimeValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*TypedValue_TimeValue); ok {
			return x.TimeValue
		}
	}
	return nil
}

func (x *TypedValue) GetDurationValue() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Kind.(*TypedValue_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

func (x *TypedValue) GetUrlValue() string {
	if x != nil {
		if x, ok := x.Kind.(*TypedValue_UrlValue); ok {
			return x.UrlValue
		}
	}
	return ""
}

func (x *TypedValue) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Kind.(*TypedValue_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

type isTypedValue_Kind interface {
	isTypedValue_Kind()
}

type TypedValue_IntegerValue struct {
	// Integer value.
	IntegerValue int64 `protobuf:"varint,1,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type TypedValue_NumberValue struct {
	// Floating-point number value.
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type TypedValue_StringValue struct {
	// Free-form string value.
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type TypedValue_BoolValue struct {
	// Boolean value.
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type TypedValue_TimeValue struct {
	// Timestamp value.
	TimeValue *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time_value,json=timeValue,proto3,oneof"`
}

type TypedValue_DurationValue struct {
	// Duration value.
	DurationValue *durationpb.Duration `protobuf:"bytes,6,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type TypedValue_UrlValue struct {
	// URL value (must be a valid absolute URL).
	UrlValue string `protobuf:"bytes,7,opt,name=url_value,json=urlValue,proto3,oneof"`
}

type TypedValue_JsonValue struct {
	// JSON value (must be valid JSON).
	JsonValue string `protobuf:"bytes,8,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

func (*TypedValue_IntegerValue) isTypedValue_Kind() {}

func (*TypedValue_NumberValue) isTypedValue_Kind() {}

func (*TypedValue_StringValue) isTypedValue_Kind() {}

func (*TypedValue_BoolValue) isTypedValue_Kind() {}

func (*TypedValue_TimeValue) isTypedValue_Kind() {}

func (*TypedValue_DurationValue) isTypedValue_Kind() {}

func (*TypedValue_UrlValue) isTypedValue_Kind() {}

func (*TypedValue_JsonValue) isTypedValue_Kind() {}

// ConfigValue represents a single configuration value at a point in time.
type ConfigValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dot-separated field path (e.g. "payments.fee").
	FieldPath string `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// The typed value. Absent when the field value is null.
	Value *TypedValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Checksum of the value (xxHash). Used for optimistic concurrency control
	// in SetField/SetFields via expected_checksum.
	Checksum string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// Human-readable description explaining this specific value.
	// Only populated when include_description(s) is true in the request.
	Description   *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValue) Reset() {
	*x = ConfigValue{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValue) ProtoMessage() {}

func (x *ConfigValue) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValue.ProtoReflect.Descriptor instead.
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigValue) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *ConfigValue) GetValue() *TypedValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigValue) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *ConfigValue) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// ConfigVersion represents a point-in-time snapshot of configuration changes.
// Each write operation (SetField, SetFields, RollbackToVersion) creates a new
// config version. Versions store only the changed fields (delta storage) — the
// full config at any version is the union of all deltas up to that version.
type ConfigVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned unique identifier (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The tenant this version belongs to (UUID).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Version number (monotonically increasing, starting at 1).
	Version int32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Description of what changed in this version.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The actor who created this version (from JWT subject, or "unknown" if auth is disabled).
	CreatedBy string `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// When this version was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVersion) Reset() {
	*x = ConfigVersion{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVersion) ProtoMessage() {}

func (x *ConfigVersion) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVersion.ProtoReflect.Descriptor instead.
func (*ConfigVersion) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigVersion) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ConfigVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigVersion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigVersion) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ConfigVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Config represents the full resolved configuration for a tenant at a specific version.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant this config belongs to (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The version number this config was resolved at.
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// All configuration values at this version.
	Values        []*ConfigValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *Config) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Config) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Config) GetValues() []*ConfigValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// ConfigChange represents a real-time change event pushed to subscribers
// via the Subscribe streaming RPC.
type ConfigChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant whose config changed (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The new config version number created by this change.
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// The field that was changed.
	FieldPath string `protobuf:"bytes,3,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// The previous value. Absent if field was newly created or was null.
	OldValue *TypedValue `protobuf:"bytes,4,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	// The new value. Absent if field was set to null.
	NewValue *TypedValue `protobuf:"bytes,5,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	// The actor who made the change.
	ChangedBy string `protobuf:"bytes,6,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	// When the change occurred.
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChange) Reset() {
	*x = ConfigChange{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChange) ProtoMessage() {}

func (x *ConfigChange) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChange.ProtoReflect.Descriptor instead.
func (*ConfigChange) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigChange) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ConfigChange) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigChange) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *ConfigChange) GetOldValue() *TypedValue {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *ConfigChange) GetNewValue() *TypedValue {
	if x != nil {
		return x.NewValue
	}
	return nil
}

func (x *ConfigChange) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *ConfigChange) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

// AuditEntry represents a write event recorded in the audit log.
// Every config mutation (SetField, SetFields, RollbackToVersion) creates
// one or more audit entries atomically with the config change.
type AuditEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned unique identifier (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The tenant affected (UUID).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The actor who performed the action (from JWT subject).
	Actor string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// The action type (e.g. "set_field", "rollback").
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// The field that was changed. Present for set_field actions.
	FieldPath *string `protobuf:"bytes,5,opt,name=field_path,json=fieldPath,proto3,oneof" json:"field_path,omitempty"`
	// The previous value. Present for set_field actions.
	OldValue *string `protobuf:"bytes,6,opt,name=old_value,json=oldValue,proto3,oneof" json:"old_value,omitempty"`
	// The new value. Present for set_field actions.
	// For rollback actions, contains the target version (e.g. "v2").
	NewValue *string `protobuf:"bytes,7,opt,name=new_value,json=newValue,proto3,oneof" json:"new_value,omitempty"`
	// The config version number created by this action.
	ConfigVersion *int32 `protobuf:"varint,8,opt,name=config_version,json=configVersion,proto3,oneof" json:"config_version,omitempty"`
	// When the audit entry was created.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetFieldPath() string {
	if x != nil && x.FieldPath != nil {
		return *x.FieldPath
	}
	return ""
}

func (x *AuditEntry) GetOldValue() string {
	if x != nil && x.OldValue != nil {
		return *x.OldValue
	}
	return ""
}

func (x *AuditEntry) GetNewValue() string {
	if x != nil && x.NewValue != nil {
		return *x.NewValue
	}
	return ""
}

func (x *AuditEntry) GetConfigVersion() int32 {
	if x != nil && x.ConfigVersion != nil {
		return *x.ConfigVersion
	}
	return 0
}

func (x *AuditEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// UsageStats represents aggregated read usage statistics for a config field.
type UsageStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant (UUID).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The field path.
	FieldPath string `protobuf:"bytes,2,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// Total number of reads across the queried time range.
	ReadCount int64 `protobuf:"varint,3,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	// The last actor who read this field (if tracked).
	LastReadBy *string `protobuf:"bytes,4,opt,name=last_read_by,json=lastReadBy,proto3,oneof" json:"last_read_by,omitempty"`
	// When this field was last read (if tracked).
	LastReadAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_read_at,json=lastReadAt,proto3,oneof" json:"last_read_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageStats) Reset() {
	*x = UsageStats{}
	mi := &file_centralconfig_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStats) ProtoMessage() {}

func (x *UsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStats.ProtoReflect.Descriptor instead.
func (*UsageStats) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *UsageStats) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UsageStats) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *UsageStats) GetReadCount() int64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *UsageStats) GetLastReadBy() string {
	if x != nil && x.LastReadBy != nil {
		return *x.LastReadBy
	}
	return ""
}

func (x *UsageStats) GetLastReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReadAt
	}
	return nil
}

var File_centralconfig_v1_types_proto protoreflect.FileDescriptor

const file_centralconfig_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1ccentralconfig/v1/types.proto\x12\x10centralconfig.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x03\n" +
	"\x10FieldConstraints\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x01H\x01R\x03max\x88\x01\x01\x12\x19\n" +
	"\x05regex\x18\x03 \x01(\tH\x02R\x05regex\x88\x01\x01\x12\x1f\n" +
	"\venum_values\x18\x04 \x03(\tR\n" +
	"enumValues\x12$\n" +
	"\vjson_schema\x18\x05 \x01(\tH\x03R\n" +
	"jsonSchema\x88\x01\x01\x12(\n" +
	"\rexclusive_min\x18\x06 \x01(\x01H\x04R\fexclusiveMin\x88\x01\x01\x12(\n" +
	"\rexclusive_max\x18\a \x01(\x01H\x05R\fexclusiveMax\x88\x01\x01\x12\"\n" +
	"\n" +
	"min_length\x18\b \x01(\x05H\x06R\tminLength\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_length\x18\t \x01(\x05H\aR\tmaxLength\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_maxB\b\n" +
	"\x06_regexB\x0e\n" +
	"\f_json_schemaB\x10\n" +
	"\x0e_exclusive_minB\x10\n" +
	"\x0e_exclusive_maxB\r\n" +
	"\v_min_lengthB\r\n" +
	"\v_max_length\"\xfd\x02\n" +
	"\vSchemaField\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.centralconfig.v1.FieldTypeR\x04type\x12D\n" +
	"\vconstraints\x18\x03 \x01(\v2\".centralconfig.v1.FieldConstraintsR\vconstraints\x12\x1a\n" +
	"\bnullable\x18\x04 \x01(\bR\bnullable\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x05 \x01(\bR\n" +
	"deprecated\x12$\n" +
	"\vredirect_to\x18\x06 \x01(\tH\x00R\n" +
	"redirectTo\x88\x01\x01\x12(\n" +
	"\rdefault_value\x18\a \x01(\tH\x01R\fdefaultValue\x88\x01\x01\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x02R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_redirect_toB\x10\n" +
	"\x0e_default_valueB\x0e\n" +
	"\f_description\"\x84\x03\n" +
	"\x06Schema\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12*\n" +
	"\x0eparent_version\x18\x05 \x01(\x05H\x00R\rparentVersion\x88\x01\x01\x12/\n" +
	"\x13version_description\x18\x06 \x01(\tR\x12versionDescription\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\x12\x1c\n" +
	"\tpublished\x18\b \x01(\bR\tpublished\x125\n" +
	"\x06fields\x18\t \x03(\v2\x1d.centralconfig.v1.SchemaFieldR\x06fields\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x11\n" +
	"\x0f_parent_version\"\xe6\x01\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tschema_id\x18\x03 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\x05R\rschemaVersion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"l\n" +
	"\tFieldLock\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\x12#\n" +
	"\rlocked_values\x18\x03 \x03(\tR\flockedValues\"\xe7\x02\n" +
	"\n" +
	"TypedValue\x12%\n" +
	"\rinteger_value\x18\x01 \x01(\x03H\x00R\fintegerValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12;\n" +
	"\n" +
	"time_value\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimeValue\x12B\n" +
	"\x0eduration_value\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x00R\rdurationValue\x12\x1d\n" +
	"\turl_value\x18\a \x01(\tH\x00R\burlValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\b \x01(\tH\x00R\tjsonValueB\x06\n" +
	"\x04kind\"\xb3\x01\n" +
	"\vConfigValue\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.centralconfig.v1.TypedValueR\x05value\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\xd2\x01\n" +
	"\rConfigVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"v\n" +
	"\x06Config\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x125\n" +
	"\x06values\x18\x03 \x03(\v2\x1d.centralconfig.v1.ConfigValueR\x06values\"\xb4\x02\n" +
	"\fConfigChange\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1d\n" +
	"\n" +
	"field_path\x18\x03 \x01(\tR\tfieldPath\x129\n" +
	"\told_value\x18\x04 \x01(\v2\x1c.centralconfig.v1.TypedValueR\boldValue\x129\n" +
	"\tnew_value\x18\x05 \x01(\v2\x1c.centralconfig.v1.TypedValueR\bnewValue\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x06 \x01(\tR\tchangedBy\x129\n" +
	"\n" +
	"changed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"\xf4\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\"\n" +
	"\n" +
	"field_path\x18\x05 \x01(\tH\x00R\tfieldPath\x88\x01\x01\x12 \n" +
	"\told_value\x18\x06 \x01(\tH\x01R\boldValue\x88\x01\x01\x12 \n" +
	"\tnew_value\x18\a \x01(\tH\x02R\bnewValue\x88\x01\x01\x12*\n" +
	"\x0econfig_version\x18\b \x01(\x05H\x03R\rconfigVersion\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\r\n" +
	"\v_field_pathB\f\n" +
	"\n" +
	"_old_valueB\f\n" +
	"\n" +
	"_new_valueB\x11\n" +
	"\x0f_config_version\"\xf3\x01\n" +
	"\n" +
	"UsageStats\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"field_path\x18\x02 \x01(\tR\tfieldPath\x12\x1d\n" +
	"\n" +
	"read_count\x18\x03 \x01(\x03R\treadCount\x12%\n" +
	"\flast_read_by\x18\x04 \x01(\tH\x00R\n" +
	"lastReadBy\x88\x01\x01\x12A\n" +
	"\flast_read_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"lastReadAt\x88\x01\x01B\x0f\n" +
	"\r_last_read_byB\x0f\n" +
	"\r_last_read_at*\xd5\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eFIELD_TYPE_INT\x10\x01\x12\x15\n" +
	"\x11FIELD_TYPE_STRING\x10\x02\x12\x13\n" +
	"\x0fFIELD_TYPE_TIME\x10\x03\x12\x17\n" +
	"\x13FIELD_TYPE_DURATION\x10\x04\x12\x12\n" +
	"\x0eFIELD_TYPE_URL\x10\x05\x12\x13\n" +
	"\x0fFIELD_TYPE_JSON\x10\x06\x12\x15\n" +
	"\x11FIELD_TYPE_NUMBER\x10\a\x12\x13\n" +
	"\x0fFIELD_TYPE_BOOL\x10\bB\xd2\x01\n" +
	"\x14com.centralconfig.v1B\n" +
	"TypesProtoP\x01ZMgithub.com/zeevdr/central-config-service/api/centralconfig/v1;centralconfigv1\xa2\x02\x03CXX\xaa\x02\x10Centralconfig.V1\xca\x02\x10Centralconfig\\V1\xe2\x02\x1cCentralconfig\\V1\\GPBMetadata\xea\x02\x11Centralconfig::V1b\x06proto3"

var (
	file_centralconfig_v1_types_proto_rawDescOnce sync.Once
	file_centralconfig_v1_types_proto_rawDescData []byte
)

func file_centralconfig_v1_types_proto_rawDescGZIP() []byte {
	file_centralconfig_v1_types_proto_rawDescOnce.Do(func() {
		file_centralconfig_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_centralconfig_v1_types_proto_rawDesc), len(file_centralconfig_v1_types_proto_rawDesc)))
	})
	return file_centralconfig_v1_types_proto_rawDescData
}

var file_centralconfig_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_centralconfig_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_centralconfig_v1_types_proto_goTypes = []any{
	(FieldType)(0),                // 0: centralconfig.v1.FieldType
	(*FieldConstraints)(nil),      // 1: centralconfig.v1.FieldConstraints
	(*SchemaField)(nil),           // 2: centralconfig.v1.SchemaField
	(*Schema)(nil),                // 3: centralconfig.v1.Schema
	(*Tenant)(nil),                // 4: centralconfig.v1.Tenant
	(*FieldLock)(nil),             // 5: centralconfig.v1.FieldLock
	(*TypedValue)(nil),            // 6: centralconfig.v1.TypedValue
	(*ConfigValue)(nil),           // 7: centralconfig.v1.ConfigValue
	(*ConfigVersion)(nil),         // 8: centralconfig.v1.ConfigVersion
	(*Config)(nil),                // 9: centralconfig.v1.Config
	(*ConfigChange)(nil),          // 10: centralconfig.v1.ConfigChange
	(*AuditEntry)(nil),            // 11: centralconfig.v1.AuditEntry
	(*UsageStats)(nil),            // 12: centralconfig.v1.UsageStats
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
}
var file_centralconfig_v1_types_proto_depIdxs = []int32{
	0,  // 0: centralconfig.v1.SchemaField.type:type_name -> centralconfig.v1.FieldType
	1,  // 1: centralconfig.v1.SchemaField.constraints:type_name -> centralconfig.v1.FieldConstraints
	2,  // 2: centralconfig.v1.Schema.fields:type_name -> centralconfig.v1.SchemaField
	13, // 3: centralconfig.v1.Schema.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: centralconfig.v1.Tenant.created_at:type_name -> google.protobuf.Timestamp
	13, // 5: centralconfig.v1.Tenant.updated_at:type_name -> google.protobuf.Timestamp
	13, // 6: centralconfig.v1.TypedValue.time_value:type_name -> google.protobuf.Timestamp
	14, // 7: centralconfig.v1.TypedValue.duration_value:type_name -> google.protobuf.Duration
	6,  // 8: centralconfig.v1.ConfigValue.value:type_name -> centralconfig.v1.TypedValue
	13, // 9: centralconfig.v1.ConfigVersion.created_at:type_name -> google.protobuf.Timestamp
	7,  // 10: centralconfig.v1.Config.values:type_name -> centralconfig.v1.ConfigValue
	6,  // 11: centralconfig.v1.ConfigChange.old_value:type_name -> centralconfig.v1.TypedValue
	6,  // 12: centralconfig.v1.ConfigChange.new_value:type_name -> centralconfig.v1.TypedValue
	13, // 13: centralconfig.v1.ConfigChange.changed_at:type_name -> google.protobuf.Timestamp
	13, // 14: centralconfig.v1.AuditEntry.created_at:type_name -> google.protobuf.Timestamp
	13, // 15: centralconfig.v1.UsageStats.last_read_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_centralconfig_v1_types_proto_init() }
func file_centralconfig_v1_types_proto_init() {
	if File_centralconfig_v1_types_proto != nil {
		return
	}
	file_centralconfig_v1_types_proto_msgTypes[0].OneofWrappers = []any{}
	file_centralconfig_v1_types_proto_msgTypes[1].OneofWrappers = []any{}
	file_centralconfig_v1_types_proto_msgTypes[2].OneofWrappers = []any{}
	file_centralconfig_v1_types_proto_msgTypes[5].OneofWrappers = []any{
		(*TypedValue_IntegerValue)(nil),
		(*TypedValue_NumberValue)(nil),
		(*TypedValue_StringValue)(nil),
		(*TypedValue_BoolValue)(nil),
		(*TypedValue_TimeValue)(nil),
		(*TypedValue_DurationValue)(nil),
		(*TypedValue_UrlValue)(nil),
		(*TypedValue_JsonValue)(nil),
	}
	file_centralconfig_v1_types_proto_msgTypes[6].OneofWrappers = []any{}
	file_centralconfig_v1_types_proto_msgTypes[10].OneofWrappers = []any{}
	file_centralconfig_v1_types_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_centralconfig_v1_types_proto_rawDesc), len(file_centralconfig_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_centralconfig_v1_types_proto_goTypes,
		DependencyIndexes: file_centralconfig_v1_types_proto_depIdxs,
		EnumInfos:         file_centralconfig_v1_types_proto_enumTypes,
		MessageInfos:      file_centralconfig_v1_types_proto_msgTypes,
	}.Build()
	File_centralconfig_v1_types_proto = out.File
	file_centralconfig_v1_types_proto_goTypes = nil
	file_centralconfig_v1_types_proto_depIdxs = nil
}
