// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: centralconfig/v1/version_service.proto

package centralconfigv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServerVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerVersionRequest) Reset() {
	*x = GetServerVersionRequest{}
	mi := &file_centralconfig_v1_version_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerVersionRequest) ProtoMessage() {}

func (x *GetServerVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_version_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerVersionRequest.ProtoReflect.Descriptor instead.
func (*GetServerVersionRequest) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_version_service_proto_rawDescGZIP(), []int{0}
}

type GetServerVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Semantic version string (e.g. "1.2.3" or "dev").
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Git commit hash.
	Commit        string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerVersionResponse) Reset() {
	*x = GetServerVersionResponse{}
	mi := &file_centralconfig_v1_version_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerVersionResponse) ProtoMessage() {}

func (x *GetServerVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_centralconfig_v1_version_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerVersionResponse.ProtoReflect.Descriptor instead.
func (*GetServerVersionResponse) Descriptor() ([]byte, []int) {
	return file_centralconfig_v1_version_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetServerVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServerVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

var File_centralconfig_v1_version_service_proto protoreflect.FileDescriptor

const file_centralconfig_v1_version_service_proto_rawDesc = "" +
	"\n" +
	"&centralconfig/v1/version_service.proto\x12\x10centralconfig.v1\x1a\x1cgoogle/api/annotations.proto\"\x19\n" +
	"\x17GetServerVersionRequest\"L\n" +
	"\x18GetServerVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit2\x90\x01\n" +
	"\x0eVersionService\x12~\n" +
	"\x10GetServerVersion\x12).centralconfig.v1.GetServerVersionRequest\x1a*.centralconfig.v1.GetServerVersionResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/versionB\xcb\x01\n" +
	"\x14com.centralconfig.v1B\x13VersionServiceProtoP\x01Z=github.com/zeevdr/decree/api/centralconfig/v1;centralconfigv1\xa2\x02\x03CXX\xaa\x02\x10Centralconfig.V1\xca\x02\x10Centralconfig\\V1\xe2\x02\x1cCentralconfig\\V1\\GPBMetadata\xea\x02\x11Centralconfig::V1b\x06proto3"

var (
	file_centralconfig_v1_version_service_proto_rawDescOnce sync.Once
	file_centralconfig_v1_version_service_proto_rawDescData []byte
)

func file_centralconfig_v1_version_service_proto_rawDescGZIP() []byte {
	file_centralconfig_v1_version_service_proto_rawDescOnce.Do(func() {
		file_centralconfig_v1_version_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_centralconfig_v1_version_service_proto_rawDesc), len(file_centralconfig_v1_version_service_proto_rawDesc)))
	})
	return file_centralconfig_v1_version_service_proto_rawDescData
}

var file_centralconfig_v1_version_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_centralconfig_v1_version_service_proto_goTypes = []any{
	(*GetServerVersionRequest)(nil),  // 0: centralconfig.v1.GetServerVersionRequest
	(*GetServerVersionResponse)(nil), // 1: centralconfig.v1.GetServerVersionResponse
}
var file_centralconfig_v1_version_service_proto_depIdxs = []int32{
	0, // 0: centralconfig.v1.VersionService.GetServerVersion:input_type -> centralconfig.v1.GetServerVersionRequest
	1, // 1: centralconfig.v1.VersionService.GetServerVersion:output_type -> centralconfig.v1.GetServerVersionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_centralconfig_v1_version_service_proto_init() }
func file_centralconfig_v1_version_service_proto_init() {
	if File_centralconfig_v1_version_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_centralconfig_v1_version_service_proto_rawDesc), len(file_centralconfig_v1_version_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_centralconfig_v1_version_service_proto_goTypes,
		DependencyIndexes: file_centralconfig_v1_version_service_proto_depIdxs,
		MessageInfos:      file_centralconfig_v1_version_service_proto_msgTypes,
	}.Build()
	File_centralconfig_v1_version_service_proto = out.File
	file_centralconfig_v1_version_service_proto_goTypes = nil
	file_centralconfig_v1_version_service_proto_depIdxs = nil
}
